### ISSUE TITLE
Comments are displayed with a different indentation

### ISSUE THREAD

**Issue by luruke** [BabylonJS/Spector.js#100]
Hi there!

When I inspect or edit the following shader:

```glsl
    precision highp float;
    
    uniform vec3 color; // ms({ value: '#ff0000' })
    uniform float brightness; // ms({ value: 0, range: [0, 0.5], step: 0.1 })
    uniform vec2 dummyValue; // ms({ value: [1024, 768], range: [[0, 2000], [0, 1500]] })
    uniform bool visible; // ms({ value: 1, name: 'Visibility' })
    uniform int test; // ms({ value: 0 })

    void main() {
      gl_FragColor = vec4(color + brightness, 1.0);
    }
```

is displayed like this:

![Screen Shot 2019-04-05 at 11 56 00](https://user-images.githubusercontent.com/61326/55619837-cf3cec80-5799-11e9-9e50-a0c2cfa52114.jpg)

and by consequence, after edited, the shader is broken.

**Comment by luruke** [comment]
I guess the problem it's here?
https://github.com/BabylonJS/Spector.js/blob/64e3269c96ebe2d38f951a14f50e9137ee4a2e80/src/embeddedFrontend/resultView/sourceCode/sourceCodeComponent.ts#L136

I guess the identation should be avoided if it's a comment

**Comment by sebavan** [comment]
ohhhhh you are totally right, Good catch :-)

I will fix it ASAP.

**Comment by luruke** [comment]
@sebavan , thanks for the quick reply...who ever thought to put curly brackets in comments, right? 😅

**Comment by sebavan** [comment]
Lol, I have to admit I did not hit this one so far :-)

**Comment by sebavan** [comment]
Do you have a live URL I could validate the fix on ?

**Comment by luruke** [comment]
Hey @sebavan , much better, but comments goes on a new line:
![Screen Shot 2019-04-07 at 11 43 11](https://user-images.githubusercontent.com/61326/55681756-5751fc00-592a-11e9-8331-3dc3b0ca8822.jpg)

I do not have a live link..but you can try it on this repo:

```
git clone git@github.com:luruke/magicshader.git
cd magicshader
npm install
npm run dev
```

Would it be possible to keep them on the same line as the original shader source?

**Comment by sebavan** [comment]
I can repro locally, do you have a strong deadline on this one ?

It sounds a bit lower priority as it does not break the full edition, and I am trying atm to move the front end to React to ease the contribution. Is a fix by end of week OK ?

**Comment by luruke** [comment]
Hey @sebavan , no worries, there is no deadline 👍😊

**Comment by sebavan** [comment]
Sweeet I will redeploy at the end of the week then.

**Comment by luruke** [comment]
Hi @sebavan, Is there any news on this?
Can I help you somehow?

Cheers!

**Comment by sebavan** [comment]
Yup the migration to React is delaying me a bit, but if you want you can definitely help by taking a look at the beautify method :-) cause I won t be able to work on it before at least another week

**Comment by luruke** [comment]
@sebavan ok, thanks. I'll see If I can do a PR :)

**Comment by sebavan** [comment]
Thanks a ton
