### ISSUE TITLE
Limit texture preview height

### ISSUE THREAD

**Issue by luruke** [BabylonJS/Spector.js#108]
I do use spector a lot for debugging FBO.
The texture used may have sizes like `1x1024`, as the preview has `100% width`, proportionally the height is huge.

![Screen Shot 2019-06-15 at 01 51 59](https://user-images.githubusercontent.com/61326/59544181-3997a900-8f10-11e9-8b7c-658c9cfa5f59.jpg)

This results in endless scrollbars.

Maybe we should set a max height, and make the width auto

**Comment by sebavan** [comment]
yup sounds like a good idea. I ll try to do it next week.

**Comment by sebavan** [comment]
@luruke I am so behind with those tasks :-( would you mind creating a PR for it ?

**Comment by luruke** [comment]
@sebavan will try to 👍

**Comment by sebavan** [comment]
Thanks again
