### ISSUE TITLE
Uniform ID does not match 

### ISSUE THREAD

**Issue by drawmindmap** [BabylonJS/Spector.js#109]
There is uniform2f command in command list:
uniform2f: WebGLUniformLocation - **ID: 63**, 0, 1

Then, select drawElements/drawArrays command, it shows this on the right side:
Uniforms(0)
name: direction
size: 1
type: FLOAT_VEC2
location: WebGLUniformLocation - **ID: 259**
value: 0, 1

It will be very helpful if these two IDs match.

**Comment by sebavan** [comment]
Hello,

Are you doing another getLocation or reusing the same gl object ???

They will only match if reusing the same object, it actually helps catching to many getLocation. If you are reusing the same objects it sound like a bug. Would be amazing if you have a repro.

**Comment by drawmindmap** [comment]
This one can [reproduce the problem](https://drawmindmap.github.io/webgl2-training/tutorials/13-camera.html).
There is no requestAnimationFrame, so after you click record, then click reload 
Uniform gl commands:
```
uniformMatrix4fv: WebGLUniformLocation - ID: 1, false, [..(16)..]
uniformMatrix4fv: WebGLUniformLocation - ID: 2, false, [..(16)..]
uniform3f: WebGLUniformLocation - ID: 3, 1, 1, 1
uniform1i: WebGLUniformLocation - ID: 4, 0
uniformMatrix4fv: WebGLUniformLocation - ID: 0, false, [..(16)..]
...
drawArrays: TRIANGLES, 0, 6VertexFragment
```
Select drawArrays:
Uniforms(0): location: WebGLUniformLocation - ID: 5 value: 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1
Uniforms(1): location: WebGLUniformLocation - ID: 6 value: 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, -4, 1
Uniforms(2): location: WebGLUniformLocation - ID: 7 value: 1, 1, 1
Uniforms(3): location: WebGLUniformLocation - ID: 8 value: 0
Uniforms(4): location: WebGLUniformLocation - ID: 9 value: 0.7827, 0, 0, 0, 0, 2.4142, 0, 0, 0, 0, -1.0020, -1, 0, 0, -0.2002, 0

**Comment by sebavan** [comment]
Ohhh, I see what you mean, yup you are totally right ids stay consistent with your apps call (getLocation and setValues) When I use instrospection through spector, as I am using getLocation as well it unfortunately returns a new instance of the location. Let me see if I can find an easy fix.

**Comment by sebavan** [comment]
It is far from being straightforward unfortunately. I am closing it for now.
