### ISSUE TITLE
Framebuffer format limitations

### ISSUE THREAD

**Issue by guycalledfrank** [BabylonJS/Spector.js#11]
Tried capturing "After the Flood" demo: https://playcanv.as/e/p/44MRmJRU/
Got this in console:
"glReadPixels: format and type incompatible with the current read framebuffer"
Unsurprisingly, no frame captures were produced. Demo uses R11G11B10 format for rendering.

**Comment by sebavan** [comment]
Thanks for reporting it, I even have the issue with float currently. I ll probably do a first quick worrkaround with cpu conversion even if that is slowing down the capture, this would be less intrusive on the gpu side.

**Comment by sebavan** [comment]
Can not capture it afterwards, this will be taken in account as part of the issue #1 implementation

**Comment by sebavan** [comment]
@guycalledfrank It is now ok in the store extension. I noticed some of the 2d sampler do not show up in the capture like your texture_diffuseMap. Are they by any chance compressed texture ? if not, what function are you using to upload the data ?

I am trying to be fully compatible with After the flood which is an amazing use case to try capturing.

Thank you,

**Comment by guycalledfrank** [comment]
Thanks, I'll check the updated version!
Yeah, we use DXT compression for material maps on PC. Do you have problems previewing those on a page?

**Comment by sebavan** [comment]
I am not supporting them yet (only the texture2d command) so that is why :-) I ll open an issue for issue so you can follow the status.

**Comment by guycalledfrank** [comment]
Sure. Probably the best way to preview any kind of texture is to draw a quad into an RGBA8 render target and then read it back, but that's just a first idea that came to my mind.
