### ISSUE TITLE
 add an option to display the actual texture size

### ISSUE THREAD

**Issue by matrix3d** [BabylonJS/Spector.js#111]
View textures can only view thumbnails of fixed size, can you add an option to display the actual size. Because I am doing a 2d webgl project now. Need to display the actual size, thank you

**Comment by sebavan** [comment]
Yup it is unfortunately a restriction to ensure most captures fit in memory. At first, we were using real size pictures but the memory was exploding real quick I wonder if we should add a checkbox to let user capture real sizes ?

**Comment by matrix3d** [comment]
The checkbox is sufficient, and the person who needs this feature is set up.

**Comment by therocode** [comment]
I'm also affected by this limitation, and a checkbox would suffice

**Comment by sebavan** [comment]
I am so sorry it takes so much time... I ll definitely deal with the open issues during the Christmas Break to start on a better way next year

**Comment by therocode** [comment]
No worries, take your time, and thank you for providing this software 👍

**Comment by sebavan** [comment]
Done and deploy, you should be able to capture full size but at your own risk depending on the actual size :-)
