### ISSUE TITLE
Spector.js not finding gl calls with Construct 3 example (browser extension)

### ISSUE THREAD

**Issue by MikalDev** [BabylonJS/Spector.js#115]
I have also tried including it in Construct 3 JS project files. It does find the appropriate canvas (which has no id defined.)

Here's an example C3 webgl2 app, so you can repo:

https://kindeyegames.com/sperf/

I will also try hacking the index.hmtl to add the spector.js sooner if possible.

**Comment by MikalDev** [comment]
I also tried adding the spector bundle and UI calls above the C3 *.js scripts in index.html and spector are still unable to find gl frames.

**Comment by sebavan** [comment]
Could you check if construct relies on an Offscreen Canvas ? it might be the main reason we are not able to capture it ?

**Comment by MikalDev** [comment]
It has an option to use an offscreen canvas (called 'worker' mode), however, I have this disabled. I have created a simpler version (from C3 standpoint), just one sprite rotating. I can use Safari web inspector to see the gl calls (vs chrome w/ spector.js - though I imagine they have tighter integration, so not surprised it works there.) Here's some of the information that I see from that, nothing obvious to me yet (it doesn't show the FB creation or bind.)
https://kindeyegames.com/spector is the 'simple' version. spector does 'see' the canvas w/ the proper dimensions.

<img width="772" alt="Screen Shot 2019-09-26 at 9 09 22 AM" src="https://user-images.githubusercontent.com/33675273/65705742-e3252500-e03d-11e9-9ebf-d5674e08c485.png">
<img width="1286" alt="Screen Shot 2019-09-26 at 9 08 50 AM" src="https://user-images.githubusercontent.com/33675273/65705743-e3252500-e03d-11e9-80c7-a6e5ef7cbcac.png">
<img width="296" alt="Screen Shot 2019-09-26 at 9 06 32 AM" src="https://user-images.githubusercontent.com/33675273/65705744-e3252500-e03d-11e9-9bbc-a9b548aa62d5.png">
<img width="642" alt="Screen Shot 2019-09-26 at 9 05 55 AM" src="https://user-images.githubusercontent.com/33675273/65705745-e3252500-e03d-11e9-989c-6dd49778b58e.png">

**Comment by MikalDev** [comment]
Perhaps another hint, it looks like the 'other' canvases may be 'detached' from the canvas node, perhaps they are being accessed somehow for the capture?

<img width="298" alt="Screen Shot 2019-09-26 at 9 35 40 AM" src="https://user-images.githubusercontent.com/33675273/65707576-ad823b00-e041-11e9-8382-c6950189d24d.png">

**Comment by sebavan** [comment]
It might be cause the canvas is not in the dom, I will check deeper on your simpler sample and let you know.

**Comment by sebavan** [comment]
Actually it looks like the frames are not detected e.g. requestAnimationFrame does not look like it can be hooked with construct.

You can use the capture button to capture a certain amount of command:
![image](https://user-images.githubusercontent.com/16655165/65711541-5dcd5f00-e095-11e9-8f14-675cd6254aa8.png)

**Comment by MikalDev** [comment]
Thanks - that works well enough for me. Great tool and nice work! Is there anything I should mention to the Construct 3 dev team to make hooking the requestAnimationFrame() call possible?

**Comment by sebavan** [comment]
I think I got to the bottom of it :-) It looks like their work in the RequestAnimationFrame is async so it totally explains why we are not capturing with the normal way.

Now I wonder how to fix this as it could potentially mean several captures overlapping and lots of gl work happening out of order. I wonder if it is intended or not ???

**Comment by sebavan** [comment]
I am closing the issue for now but feel free to continue the discussion on the topic I am pretty interesting on why this would be async inside the RAF.

**Comment by MikalDev** [comment]
I posted a query on the C3 forum to take a look at this issue thread, hopefully someone on the C3 dev team will take a quick look here and comment. I do know there is a C3 mode/option where the C3 webgl render is done in a worker thread to an offscreen canvas, not in DOM, I wonder if that is related to how it's implemented (the simple example I gave above is _not_ using this mode.)

**Comment by AshleyScirra** [comment]
The rAF callback is async because sometimes it needs to be. For example if you save a savegame, it does storage access during the tick, which is async. Similarly Construct has debugging features that require suspending the tick mid-way and inspecting its state. Since even a single use of `await` means the method must be async, it's async. The next rAF is requested at the end of the async method, so as long as it completes quickly it's fine and the framerate keeps going. However all the WebGL calls happen synchronously to guarantee they all appear in the same frame and in the right order.

I don't know anything about how spector.js works but from reading this it seems to me the obvious thing to do would be to capture everything from rAF until the next rAF callback, rather than only calls made synchronously inside the rAF callback.

**Comment by sebavan** [comment]
Yup I ll try back this approach but I was on other use cases collecting more than needed. At least having more will not hurt.

Thanks for the explanation.
