### ISSUE TITLE
Missing features report

### ISSUE THREAD

**Issue by juj** [BabylonJS/Spector.js#116]
Heya, tried to use SpectorJS to debug a real world issue, and I noticed I wanted to do the following that SpectorJS currently cannot do (to my understanding?). I hope this may be helpful:

1. Given a `bindTexture` line, it would be useful to know what the texture is that is getting bound, its size, visual contents and format. Currently SpectorJS only shows the ID of the texture that does not help much. (same goes for a draw call - it would be interesting to know what textures are bound for a draw)

2. Given a useProgram line, it would be useful to know which shaders that program contains, i.e. the vertex and fragment shader source code (Currently again only the ID of the program is shown). Also at draw call time, it would be useful to know what shaders are bound.

3. Given a FBO bind, it would be useful to know what textures/renderbuffers it consists of, their size and types. (also at draw call time)

**Comment by sebavan** [comment]
Actually, for all of them the information at bind time is not that usefull as it could all change just after. It is why we decided to put the info for each draw calls where the final values is actually used.

If you scroll down on the right panel on any draw call. you will find all the info your are looking for.

Let me know if that helps ?

**Comment by juj** [comment]
> Actually, for all of them the information at bind time is not that usefull as it could all change just after.

It would be useful to show the information at bind time, and if it gets changed just after, then show the new changed information at the new bind time. That would allow explicitly debugging redundant state sets as well, and avoid having to scroll through a call trace to find the next draw in order to find what the current useProgram/bindTexture/bindFramebuffer actually did. (of course it would have to track and show the information as it occurred at that time, and not the latest)

> If you scroll down on the right panel on any draw call. you will find all the info your are looking for.

Oh cool, thanks! Now I find that the shader source code is indeed there, so that solves 2) for me. Very nice!

However I am unable to solve 1) and 3) still. For 1), at draw time, I see

```
Uniforms(1)
name: tex
size: 1
type: SAMPLER_2D
location: WebGLUniformLocation - ID: 105
value: 0
blockIndice: -1
offset: -1
arrayStride: -1
matrixStride: -1
rowMajor: false
   Texture
   magFilter: LINEAR
   minFilter: LINEAR
   wrapS: CLAMP_TO_EDGE
   wrapT: CLAMP_TO_EDGE
   anisotropy: 1
   baseLevel: 0
   immutable: true
   immutableLevels: 1
   maxLevel: 1
   maxLod: 1
   minLod: 1
   compareFunc: LEQUAL
   compareMode: NONE
   wrapR: SYNC_FLUSH_COMMANDS_BIT
```
but that does not say what the texture is. (Would be super to see the ID, width, height, internalFormat, type, and visual appearance of the contents of the texture)

For another draw, there's

```
Uniforms(7)
name: _GUIClipTexture
size: 1
type: SAMPLER_2D
location: WebGLUniformLocation - ID: 99
value: 1
blockIndice: -1
offset: -1
arrayStride: -1
matrixStride: -1
rowMajor: false
Texture
magFilter: NEAREST
minFilter: NEAREST
wrapS: CLAMP_TO_EDGE
wrapT: CLAMP_TO_EDGE
anisotropy: 1
baseLevel: 0
immutable: true
immutableLevels: 1
maxLevel: 1
maxLod: 1
minLod: 1
compareFunc: LEQUAL
compareMode: NONE
wrapR: SYNC_FLUSH_COMMANDS_BIT
```
Seeing a sampler uniform take value `1` is interesting if that's what one is debugging an issue about, though is there a way to see what texture is actually bound to texture unit 1?

For 3), at draw time I see

```
Frame Buffer
frameBuffer: WebGLFramebuffer - ID: 0
Depth Attachment
type: RENDERBUFFER
buffer: WebGLRenderbuffer - ID: 0
internalFormat: DEPTH24_STENCIL8
width: 960
height: 600
msaaSamples: 0
alphaSize: 0
blueSize: 0
encoding: LINEAR
componentType: UNSIGNED_NORMALIZED_EXT
depthSize: 24
greenSize: 0
redSize: 0
stencilSize: 8
Stencil Attachment
type: RENDERBUFFER
buffer: WebGLRenderbuffer - ID: 0
internalFormat: DEPTH24_STENCIL8
width: 960
height: 600
msaaSamples: 0
alphaSize: 0
blueSize: 0
encoding: LINEAR
componentType: UNSIGNED_NORMALIZED_EXT
depthSize: 24
greenSize: 0
redSize: 0
stencilSize: 8
Color Attachments(0)
type: TEXTURE
texture: WebGLTexture - ID: 23
textureLevel: 0
textureCubeMapFace: NONE
alphaSize: 8
blueSize: 8
encoding: SRGB_EXT
componentType: UNSIGNED_NORMALIZED_EXT
depthSize: 0
greenSize: 8
redSize: 8
stencilSize: 0
textureLayer: 0
```

Now I'm actually wondering if `SRGB_EXT` type is preventing that framebuffer from being previewed?

**Comment by sebavan** [comment]
Yup it probably is related to the type of texture cause it is what I see from frame buffers :
![image](https://user-images.githubusercontent.com/16655165/66150492-97621500-e615-11e9-9f82-7d5f573bd77c.png)

and for textures:
![image](https://user-images.githubusercontent.com/16655165/66150542-b52f7a00-e615-11e9-909c-e7c2294e2226.png)

**Comment by juj** [comment]
Hmm, further, debugging today I am not getting shaders on draws calls, but spector is saying:
```
program Status

    program: WebGLProgram - ID: 1
    DELETE_STATUS: false
    LINK_STATUS: true
    VALIDATE_STATUS: false
    RECOMPILABLE: false

shaders: Empty Array
```

**Comment by sebavan** [comment]
This is is really strange but might happen if the shader have been deleted after linking the program.

Could you share the site you are trying to debug so that i can dig further?

**Comment by juj** [comment]
Sure, the project is at
http://clb.confined.space/dump/shdhdh_20191003_155801_asm_development_uncompressed/ , or at
http://clb.confined.space/dump/shdhdh_20191003_155801_asm_development_uncompressed/shdhdh_20191003_155801_asm_development_uncompressed.zip if you'd like a locally hostable copy.

**Comment by sebavan** [comment]
Perfect, I ll have a look later today.

**Comment by sebavan** [comment]
Shaders are all good on my side: 
![image](https://user-images.githubusercontent.com/16655165/66211571-a4860f00-e6bc-11e9-900d-c796f37a1ffd.png)

And about the frame buffer attachments,  you are right it is because we only support basic types to get texture capture.

**Comment by thomlucc** [comment]
Closing as all the comments look addressed. Please re-open if necessary.
