### ISSUE TITLE
window.location.href not restored when closing details window

### ISSUE THREAD

**Issue by Zaitsev** [BabylonJS/Spector.js#118]
I'm using sectorjs as module in react electron app with hash router
Spector opens results window on capture

![image](https://user-images.githubusercontent.com/127843/68155602-b0cae980-ff52-11e9-84f5-ffc8bcf62b2a.png)
`window.location.hash === #/anomaly_gl/history` which is right hash for captured page
bu after clicking `Close` hash becomes  `#/`. Since it is react hash router, this renders another page.

**Comment by sebavan** [comment]
Hello, could you detali a bit more the issue and when this happens ?

thanks,

**Comment by Zaitsev** [comment]
Just updated issue

**Comment by sebavan** [comment]
Oh what should the url be to not enter in conflict with yours ???

**Comment by Zaitsev** [comment]
URL should be _the same as it was_, btw url by itself is OK, but window.location.*hash* wes cleared

**Comment by sebavan** [comment]
Cool thanks.

**Comment by Zaitsev** [comment]
Offtop: is there any way to move spector to devtools tab like react and redux devtools did it. IMHO spectro IS devtool and having it there will allow to display results `in-page` and not spoil web-toolbar?
![image](https://user-images.githubusercontent.com/127843/68157113-b544d180-ff55-11e9-8489-61d016bf7788.png)

**Comment by sebavan** [comment]
might be good as an option, I am totally not opposed to it if you fancy doing a PR ?

**Comment by Zaitsev** [comment]
It would take me too much time (never did any chrome extensions....)

**Comment by Zaitsev** [comment]
> URL should be _the same as it was_, btw url by itself is OK, but window.location._hash_ wes cleared
> ie symbols after '#' in hash _should not be changed_


I'm not sure, but if _hash_  is affected then  location._search_ could be affected too , ie `?param1=val&param2=val2` part of uri

**Comment by sebavan** [comment]
Ok I ll try to do the url changes soon and keep the other one for later as a feature request. I won t be available before monday next week though when I should do the logo migration as well.
