### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by luruke** [BabylonJS/Spector.js#121]
Wondering, is there any plan to support WebGPU in the future?
Or it's more likely that it's going to be a totally new project / fork?

**Comment by sebavan** [comment]
Would be great to have it here :-) i definitely need to find time for it.

**Comment by frguthmann** [comment]
Might be interested, not sure how complicated that is :)

**Comment by sebavan** [comment]
A bit :-) cause it is stateless so might have completely different kind of caching to do :-)

**Comment by frguthmann** [comment]
Right, I've been meaning to give a hand because I use SpectorJS literally everyday. It's kind of hard to figure out a way to start, this is probably not the best one though...

**Comment by sebavan** [comment]
Yeahhhhhh, might be a tough one but we could do it at several people :-)

Basically there is 2 parts, the backend capturing and recording states, and the front displaying it. I would say at firts if we could have all the backend, then we ll see for the front. I have rewritten some of it in react and once all done it should be way easier for external contribs.

**Comment by frguthmann** [comment]
Definitely interested in understanding more about the backend and how you guys catch the different calls. Do not hesitate to ping me if you think there is something I can do. (No promises though :p)

**Comment by sebavan** [comment]
Send me a message at sevan@microsoft.com and I can organize us a quick skype call if you want ?

Would love to work on it as a community project.

**Comment by frguthmann** [comment]
Will do :)

**Comment by sebavan** [comment]
Closing for now as this will be in another repo/tool for the best ;-)

**Comment by kohakukun** [comment]
May I ask which repo? If already created 😄

**Comment by sebavan** [comment]
not yet but the technique will need to be quite different :-)

**Comment by kohakukun** [comment]
Still interested at developing it as a community project? I would be interested

**Comment by sebavan** [comment]
Most definitely, i ll start in about a month if everything goes well :-) I ll ping you then

**Comment by frguthmann** [comment]
Can't wait to see what you're brewing. Pix works really well with WebGPU but we could definitely use a SpectorJS level kind of tool as well :).

**Comment by kohakukun** [comment]
@sebavan Just a friendly reminder if you have the bandwidth to start the WebGPU tool and want a helping hand (sorry to be using this channel, I didn't find another channel)

**Comment by sebavan** [comment]
I definitely want to start it cause it would be awesome :-)

As we are currently close to launch the latest release of Babylon I do not have a lot of free time to work on it at the moment but I ll ping you as soon as I start :-)

**Comment by fedegratti** [comment]
Hi @sebavan I hope you are doing well! 

did you start working on this? 

thank you

**Comment by sebavan** [comment]
WebGPU is so different that Spector is not the best fit. An early debugger was started here: https://github.com/webgpu/webgpu-debugger and we currently use pix to troubleshoot in our team. I wish I had more time to work on this !!!
