### ISSUE TITLE
Capturing FBO

### ISSUE THREAD

**Issue by elalish** [BabylonJS/Spector.js#124]
The documentation is a bit sparse on how to use `transient` and the `capture/reload` buttons at the bottom. It seems like they should allow for the capturing of draw calls that happen on page load, usually to FBOs, rather than the default framebuffer, for things like PMREM generation. However, I can only seem to capture the animation loop no matter what combinations of buttons I try. I vaguely recall I had gotten this to work at some point, but I can't repro it now, so I'm beginning to doubt myself. 

Should this be possible? If so, how?

**Comment by sebavan** [comment]
Transient would mean that you could capture canvases not part of the dom when checked.

Capture is meant to start capturing the next requested number of commands independently of RAF or render loop.

Reload will reload the page and start capturing ASAP the requested number of commands.

Is it a bit clearer ? if yes I ll make sure to adapt the documentation ?

**Comment by elalish** [comment]
Ah, interesting. It works as you say when select `Show offscreen canvas(es)` and `transient` and then click `Reload` at https://modelviewer.dev. However, when I try that here: https://threejs.org/examples/#webgl_loader_gltf it reloads the page, but does not capture anything. Do you have any idea what the difference is?

As for documentation, if the `capture` button at the bottom of the dialog really does exactly the same thing as the red circle, I'd replace the `Capture/Reload` buttons with a single `Reload & Capture` button, as that would be more clear.

**Comment by sebavan** [comment]
Unfortunately it is linked to the way the canvas is dynamically created in 3 and not belonging to the html.

The Capture at the bottom does not do the same, it captures for a certain amount of commands whilst the top one capture a frame. The first one will usually might capture more or less than a frame.

**Comment by elalish** [comment]
I see, that's helpful, thanks! I also noticed one other minor thing about FBOs: when I have multiple render calls that draw to different portions of the FBO, the thumbnail always shows the result drawn in the lower-left corner (ignoring x and y of viewport) and shows the rest of the FBO as blank (even though it's not). This makes it a bit harder to debug, as you can't tell if your viewport has been set incorrectly.

**Comment by sebavan** [comment]
Oh good catch, I ll try to update the documentation and fix the viewport issue quickly.
