### ISSUE TITLE
Firefox version missing

### ISSUE THREAD

**Issue by Querijn** [BabylonJS/Spector.js#125]
It seems that the Firefox version is no longer available?
https://addons.mozilla.org/en-US/firefox/addon/spector-js/

**Comment by sebavan** [comment]
Let me check my mails... it happened once already cause they were not able to compile it from the scripts I will try to fix it ASAP

**Comment by sebavan** [comment]
So like #120, the extension does not pass the review for addons :-(

@Querijn I am sorry about this but might take a bit more time for this one...

@digitalrad, I am sorry this happens again but this time the reviewers built it and the vendors library (same since more than 2 years without changes) are now rejected. The file in question is a none minified lib where I brought some custom modif to change style colors only. And unfortunately I do not remember what version it was.

I will try to see if it is easy to update and if not it might take some time before I will be able to fix it.

**Comment by Querijn** [comment]
No worries! Good luck. Sorry to have brought this to your attention during the weekend/holidays.

**Comment by sebavan** [comment]
No problem, it is better to know it despite how annoying it is :-) I am updating at the moment and it looks like I should be able to solve it over the weekend.

**Comment by sebavan** [comment]
Should be all good by now but let see what happened in 2 weeks :-)

**Comment by digitarald** [comment]
@sebavan, just confirming – you got the messages from the addons review team, right, and everything is resolved?

**Comment by sebavan** [comment]
@digitarald  Yup I resolved the issue and I am waiting for the next manual review :-) to see if it is now all good

**Comment by sebavan** [comment]
@digitarald It looks I am currently block with the review and I asked Zephyr the reviewer to contact you for my latest submission.

As I had to modify slightly ace and the other plugin I rely upon to accomodate css and glsl, it looks like I won t be able to pass the review. (It has always been the case in the plugin)

I unfortunately do not have enough time to solve those issues only for the FF addon, so would be glad if you could help on my submission. Like I explained on the submission thread, I do not want to drop the support for FF altogether but it looks more and more the likely outcome :-(

**Comment by digitarald** [comment]
@sebavan I totally understand your position and am sorry about the extra back and forth this has caused. The right person on the addons team is out, but I'll make sure people are aware and and will follow up further next year.

**Comment by kewisch** [comment]
Hi @sebavan, chiming in from the add-ons team here. I've already answered via the tools where all our reviewers can see the messages, but I wanted to check in here as well. We'd love for you to continue supporting Firefox and hope there is a way you can accommodate for our policies. You say the changes are slight, maybe there is a way to separate the changes from the library itself so we can checksum the library and review your changes separately.

Let's continue discussion on the reviewer tools. I'm going to be out for the holidays, but Zephyr will be available for questions and I'll check in on this when I get back.

**Comment by digitarald** [comment]
Looks like https://addons.mozilla.org/en-US/firefox/addon/spector-js/ is up again. Can this be closed or can I help with any follow up?

**Comment by sebavan** [comment]
So I published a new release yesterday which I hope will be all good but I normally know only about 7 days after if it is the case :-) so Let s track it for 10 more days.
