### ISSUE TITLE
Spector.js stopped working today on Chrome Linux

### ISSUE THREAD

**Issue by elalish** [BabylonJS/Spector.js#128]
It was working just fine, I'd just looked at a capture, then I went to take another and suddenly it would no longer list my offscreen canvases. I restarted Chrome, and now the Spector.js symbol is red, but if I click it, it doesn't turn green, it just gives me the generic "manage this extension" menu. I'm on Chrome 79 on a Debian-like Linux desktop.

**Comment by sebavan** [comment]
whoooot so weird... Do you see any errors ? in the console or anything that could help troubleshooting ?

**Comment by sebavan** [comment]
As it works on both Win and Mac, might it be a Chrome issue ?

Also I wonder if you had an update of the extensions during your capture, you could try closing the browser and reopen just to see

**Comment by elalish** [comment]
There's nothing in the console; not sure where I'd look for extension errors. It's giving me the exact same behavior now on Chrome on my Macbook Pro as well.

**Comment by elalish** [comment]
I've tried restarting the browser, to no avail. Here is one of the sites I'm testing, which used to work fine: https://modelviewer.dev/

**Comment by sebavan** [comment]
So it does not work on windows as well and probably cause the rendering does not happen in a direct way, I ll have a look shortly. maybe it relies on offscreen canvas or similar.

**Comment by sebavan** [comment]
Does it work for you on https://playground.babylonjs.com/ on Linux ???

**Comment by sebavan** [comment]
On the three js model viewer it looks like offscreenCanvas is in use:

![image](https://user-images.githubusercontent.com/16655165/71293285-3543c100-2375-11ea-8a72-d0781aa3611d.png)

Which we do not support so we can not activate the extension as we do not think there are any canvases in the page.

**Comment by elalish** [comment]
Ack, you're right! We made a switch to enable offscreen canvas this morning. I didn't even realize it, but this must have happened when I pulled in that change.

**Comment by sebavan** [comment]
I ll close this one as a dup of https://github.com/BabylonJS/Spector.js/issues/90 then. And I whish Santa will bring me time for Christmas :-)
