### ISSUE TITLE
Problems with webGL2 in sketchfab

### ISSUE THREAD

**Issue by jtorresfabra** [BabylonJS/Spector.js#13]
hi, 
Just experienced a crash due to spector.js. 

Try any scene with the flag ?webgl2=1 at the end, like:

https://sketchfab.com/models/4d9f1a93a4a04b08aec30a8f2f9c6fa2?webgl2=1

A nice crash appear in the screen when spector.js is on.

**Comment by sebavan** [comment]
Nice, thank you for reporting, I guess I will change my strategy for gathering available contexts.

I will fix it tomorrow on Fix Day.

**Comment by sebavan** [comment]
Bug is fixed on master, I plan to push the new version of the extension over the weekend. In the meantime, you can sideload locally.

**Comment by sebavan** [comment]
@jtorresfabra All good now and published in the chrome extension store.

**Comment by jtorresfabra** [comment]
Sorry for the late reply, thank you!

**Comment by sebavan** [comment]
No problem and do not hesitate if you spot other issues, I am keen on fixing as most as I can.
