### ISSUE TITLE
Add option to display pre-processed shader

### ISSUE THREAD

**Issue by frguthmann** [BabylonJS/Spector.js#132]
I know it has been mentioned before, but being able to read the shader once the preprocessor step was applied to it would be of tremendous help.

Use case examples:
Do not display code that is not actually executed and gets in the way of readability
Figure out that some code is missing because you forgot a define

**Comment by sebavan** [comment]
Yeah, unfortunately, it is not possible as we would have to interpret macros fully and all their gotchas to do that.

Macros can be hell to handle correctly and I prefer to not do it than doing it badly. Now if you find a nice preprocessor in JS I am open to integrate it.

This is the main reason we closed it last time :-)

Let s reopen it if we find a nice external package to handle it ???

**Comment by frguthmann** [comment]
Right, I understand. I'm using this one when I really need it but it's probably (most definitely?) not production ready. https://github.com/AndrewRayCode/glsl-preprocessor

If someone were to expose the pre-processor from glslang and compile it to WebAssembly, would that work with you? Not sure if that's possible or even relevant but I don't think anyone will make a nice GLSL pre-processor in JS anytime soon.

I didn't know it was opened before, sorry!

**Comment by sebavan** [comment]
Yup the glslang one in wasm would be great :-) and I agree this would be ideal. Cause I tried to use the optimized version from the debug extension but unfortunately It is not as understandable.
