### ISSUE TITLE
Suddenly spector UX is super unresponsive on Chrome Linux

### ISSUE THREAD

**Issue by elalish** [BabylonJS/Spector.js#133]
Everything is working for capture, but when I click to open a shader and try to scroll through it, it will take many seconds to respond to my scroll, or pretty much any other input. At one point it got so unresponsive that I think the whole extension crashed, as the icon no longer responds to clicks.

**Comment by sebavan** [comment]
Ohhhhh we updated recently Ace.js, the editor library we are using. I hope it is not related. Do you happen to have a repro site ?

Else I ll revert to the previous editor version.

**Comment by elalish** [comment]
Try any of these: https://threejs.org/examples/#webgl_materials_variations_standard

**Comment by sebavan** [comment]
Ok, it is slow as well on windows :-( let me check if it is the editor update but as it feels slowish in general, I wonder if it is not the entire rendering we are using I ll keep you posted ASAP.

**Comment by sebavan** [comment]
Can you please try on https://playground.babylonjs.com/#G3GZA1#49 and let me know ?

Would like to be sure it is the code beautifier in use when no edit is possible.

**Comment by sebavan** [comment]
Yup, looks more and more like it could be the latest version of PRISM. @elalish if you confirm you do not have with shaders of https://playground.babylonjs.com/#G3GZA1#49 I ll use ace.js in readonly mode instead and re deploy ASAP.

**Comment by elalish** [comment]
I'm guessing you've already redeployed because everything is working great now. Thanks!

**Comment by sebavan** [comment]
I did not :-) so something is strange with latest. I close it but please. @elalish let me know if that happens again and we ll make sure to track it down.

**Comment by elalish** [comment]
@sebavan Strange, it now seems sort of in-between. Perhaps it did crash and restart and that got it working again? It seems to be getting steadily slower. Maybe some kind of memory leak?

**Comment by sebavan** [comment]
ohhhhhh interesting and is it slow on  https://playground.babylonjs.com/#G3GZA1#49  as well ?

Trying to understand if the leak is in the beautifier ?

**Comment by elalish** [comment]
@sebavan Interesting, your link works fine, even when I spector it. I've also spectored my link above, and mine has terrible performance while yours is good. The primary difference seems to be that the shaders in my link are much longer.

**Comment by sebavan** [comment]
Ok so it looks like the newer version of prism we use to be compliant with firefox compliance policies is the culprit :-( I will try to create an ace only based version over the week end to solve it. Thanks a lot for your report.

**Comment by sebavan** [comment]
Should be "fixed" on latest (currently in review in the chrome extension dashboard)

Fixed is quoted cause I replaced the shader beautifier which was creating the slow behavior by the one we use for editable shaders.

All available in v0.9.13
