### ISSUE TITLE
Firefox 72.0 error: "OffscreenCanvas is not defined"

### ISSUE THREAD

**Issue by marquizzo** [BabylonJS/Spector.js#137]
Hello! I've been using Spector.js in Firefox for over a year with great results. However, today I noticed that the "Debug with Spector" button was grayed out with no ability to enable it, and I encountered an error in my dev console that says:

> ReferenceError: OffscreenCanvas is not defined.

I looked into this issue, and it looks like `OffscreenCanvas` only [has limited support in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/OffscreenCanvas#Browser_compatibility) and to enable it in the latest versions (72.0, but possibly earlier), we have to go into the Firefox preferences by visiting `about:config` and set `gfx.offscreencanvas.enabled` to `true`. Once this is toggled, the extension works as expected.

I just thought I'd let you know about this obstacle. Is there a more user-friendly way to enable this setting through the extension?

OS: Mac OS 10.13.6
Browser: Firefox 72.0

**Comment by sebavan** [comment]
Found it, thanks for reporting, it is a side-effect (meaning my big fingers messing up ;-) ) of the OffscreenCanvas support addition, I ll rollout a Fix ASAP.

**Comment by sebavan** [comment]
@marquizzo You can update your extension and it should be all good, I just deployed it

**Comment by marquizzo** [comment]
That was super fast. Thank you!
