### ISSUE TITLE
[Feature request]: Trigger Spector.js to save frame on a condition

### ISSUE THREAD

**Issue by SukantPal** [BabylonJS/Spector.js#139]
https://stackoverflow.com/questions/43910020/how-to-communicate-between-frame-and-edge-extension-content-script

Based off the link above, could Spector.js implement a feature where a WebGL application can trigger Spector.js to save the "debugging" of the current frame? To prevent a DOS-like situation, a 
"limit" could be implemented & a switch for this on the UI side?

**Use Case**: I am implementing caching system, which is triggered based off of uncontrollable variables (like FPS). In order to debug it in a real-world environment, I need to be able to tell Spector.js _when_ to save the current frame. The only feasible way I see to do that is to add Javascript on my side to tell it to do so.

Any suggestions?

**Comment by sebavan** [comment]
as long as spector is enabled, a spector instance is available in the window so you could run spector.captureCanvas(...) to save the next frame.

Is it what you are trying to achieve ?

**Comment by SukantPal** [comment]
@sebavan Sounds interesting, I think that will solve my problem. Do you have a link that documents this?

**Comment by sebavan** [comment]
https://github.com/BabylonJS/Spector.js/blob/master/documentation/apis.md#spectorspector you can find what is available on the spector instance
