### ISSUE TITLE
DXT internal format size missing

### ISSUE THREAD

**Issue by ivanpopelyshev** [BabylonJS/Spector.js#140]
Thanks from PixiJS team for a wonderful tool! 

I'm debugging an app with big number of `.dds` resources, and I found that `baseRecorder` doesnt contain the size for most of compressed texture formats.

https://github.com/BabylonJS/Spector.js/blob/1313c95a0e416ce17c7f404c3bf47a731e5a4554/src/backend/recorders/baseRecorder.ts#L23

In my case its `COMPRESSED_RGBA_S3TC_DXT5_EXT`.

The size is defaulting to `4`: https://github.com/BabylonJS/Spector.js/blob/1313c95a0e416ce17c7f404c3bf47a731e5a4554/src/backend/recorders/baseRecorder.ts#L200

**Comment by Busyrev** [comment]
I think that it should be better to show warning to user, not just shallow unknown texture format here https://github.com/BabylonJS/Spector.js/blob/1313c95a0e416ce17c7f404c3bf47a731e5a4554/src/backend/recorders/baseRecorder.ts#L200

**Comment by ivanpopelyshev** [comment]
Btw, it also doesnt take into account type of texture in case of WebGL1: FLOAT textures there have internalFormat RGBA and not RGBA32F.

**Comment by sebavan** [comment]
Yup, totally agree with that, unfortunately I am totally short on time these days, do you want to create a PR for it ?

**Comment by ivanpopelyshev** [comment]
I'm on it

**Comment by ivanpopelyshev** [comment]
Btw, its not a bug. According to what I saw in the source code - its more a features-request.
