### ISSUE TITLE
Spector.js switches vertex & fragment shaders

### ISSUE THREAD

**Issue by SukantPal** [BabylonJS/Spector.js#143]
I just found out that Spector.js is reporting my vertex shader as the fragment & my fragment shader as the vertex.

<img width="1671" alt="Screen Shot 2020-02-21 at 6 27 08 PM" src="https://user-images.githubusercontent.com/22450567/75079736-c64f2980-54d7-11ea-8f2a-c65afa3ba621.png">

`gl_FragColor` is not supposed to be set in the vertex shader as Spector.js is showing above.

**Comment by sebavan** [comment]
w0000000t ?!? this is so weird :-)

Could you share a repro page I could use to troubleshoot ???

I have never experienced this behavior I should be back from vacation shortly to fix it as soon as I have the repro @SukantPal .

**Comment by sebavan** [comment]
@SukantPal  any update on this ? I can not find a way to repro unfortunately :-(

**Comment by sebavan** [comment]
Closing as no repro for now feel free to reopen if you find a repro.

**Comment by sebavan** [comment]
Oh I think I know where it could be, it will be fixed in the next release.
