### ISSUE TITLE
Shaders not being shown on scenes using three.js

### ISSUE THREAD

**Issue by vlucendo** [BabylonJS/Spector.js#145]
Hello,

I've noticed recently that when inspecting scenes built with latest three.js versions it is not possible to have a look at the shaders. You can test it with any of their examples.

Thanks for the awesome tool!

**Comment by sebavan** [comment]
Maybe they are not deleting them after linking so spector can not introspect them anymore. This is related to https://github.com/BabylonJS/Spector.js/issues/89

**Comment by sebavan** [comment]
Yup this is the exact same issue :-( https://github.com/mrdoob/three.js/commit/9d19bd987e8fd95d1c8b71cb961491868a767336

I ll see if there is an easy workaround over the weekend.

**Comment by vlucendo** [comment]
Here's the discussion: https://github.com/mrdoob/three.js/pull/18402
This is such a nice feature, hope we can keep it :/

**Comment by sebavan** [comment]
Yup, I agree, as the memory constraints where usually not as big we kept them in Babylon cause it was way easier for spector :-)

That said I ll do both as well if I fix it for three.

**Comment by sebavan** [comment]
Should be deployed on Monday, it is currently in review by the chromium team.

**Comment by vlucendo** [comment]
awesome man, you're a legend!
