### ISSUE TITLE
Capturing does not always work

### ISSUE THREAD

**Issue by juj** [BabylonJS/Spector.js#150]
E.g. when visiting http://clb.confined.space/dump/PolyStyleMedievalVillage_20200418_065906_wasm_release_cpuprofiler/ for some reason Spector.js is unable to capture the page.

See video at
http://clb.confined.space/dump/SpectorJs_capturing_does_not_work.mov

It seems that Spector is unable to find the canvas on the page. It asks to select the canvas, but not quite sure how to exactly do it?

**Comment by sebavan** [comment]
This is related to  the thumbnails capture being pretty slow as capturing each of them is a pain and requires lot of extra copies to a canvas 2d before converting the picture to base64 to keep them serialized :-( You can use
 
![image](https://user-images.githubusercontent.com/16655165/79640403-c135f000-8191-11ea-82f9-a1a4c72b1bf2.png)

which is less than ideal but can at least help seeing the command.

That said like on #151 I do not see how exploring the capturing can be manageable in 40 000 calls.

I guess the easiest in those app is to debug by relying on the npm package or we could reorganize the UI per Frame Buffer as it has been proposed once ? I am taking any idea where we could reduce the amount of visible info to make the navigation useful

**Comment by juj** [comment]
Hmm, are you sure? Note that the missing canvas issue occurs already before I do a capture. Does Spector.js capture thumbnails already before clicking on capture?

To be precise, the issue here is not that capture takes a long time on the page, but that it often happens that one cannot even initiate taking a capture of the page, as the profiler gets stuck saying "please choose a canvas in the list" and no canvases show up in the list?

**Comment by juj** [comment]
(I would not mind even if doing a full capture would take 10-20 minutes on such a long page)

**Comment by sebavan** [comment]
Ohhhhh my bad, i was lucky on my couple tries then, i ll see if I can easily repro :-) thanks for the precisions.

**Comment by sebavan** [comment]
I am not able to repro consistently, so the easiest here might be to use the npm package.
