### ISSUE TITLE
Intermediate framebuffers are not always shown

### ISSUE THREAD

**Issue by juj** [BabylonJS/Spector.js#152]
E.g. in a profile of http://clb.confined.space/dump/unity/Wasm-Tiny3D/Tiny3D.html

Spector.js is unable to render all the screenshots from intermediate renders, see FBO 0 on the left:

<img width="1317" alt="Screen Shot 2020-04-18 at 9 27 41 AM" src="https://user-images.githubusercontent.com/225351/79630059-fec95780-8156-11ea-9e4a-126da307070c.png">

**Comment by sebavan** [comment]
This is normal as we only capture colored buffer and this is only a depth component one. It is a tradeoff to ensure a tiny bit more perfs as we would need a new render and changing the webgl state quite a bit to convert into a color buffer.

Would be cool to add an option to do it on demand if you fancy doing a PR ?

I am closing this one, and I am looking into the other ones.

**Comment by juj** [comment]
Oh I see.. perhaps if the thumbnail image is not shown, it would make sense to instead print the format of the target, e.g. "Depth16 FBO not captured"?

**Comment by sebavan** [comment]
Totally agree I ll do that ASAP :-)

**Comment by lucaheft** [comment]
It seems like visualizing depth maps is still not possible.
![image](https://github.com/BabylonJS/Spector.js/assets/1641794/31472864-ee4b-49e6-b11a-6a8a8ea66f6e)
Would love to see this, as this would be extremly helpfull for implementing shadow mapping!
