### ISSUE TITLE
Spector not capturing canvases that don't refresh on each frame.

### ISSUE THREAD

**Issue by marquizzo** [BabylonJS/Spector.js#153]
When visiting this page http://mattdesl.github.io/glsl-fxaa/demo/ I'd like to take a look at the FXAA shader code with Spector.js However, when I hit "record", nothing captures because the scene isn't re-rendering on each frame. After a few seconds it gives me the error:

> "No frames detected. Try moving the camera or implementing requestAnimationFrame."

I try clicking on the canvas to trigger new renders, but by then Spector closes and it no longer attempts to capture anything. Is there a method to capture frames that don't animate within `requestAnimationFrame`?

**Comment by sebavan** [comment]
You can use the capture button at the bottom to capture the next X commands and then  click the picture to create commands:

![image](https://user-images.githubusercontent.com/16655165/81945540-87c09b00-95fe-11ea-8228-2aa95c15ff42.png)

**Comment by marquizzo** [comment]
Ah, I didn't know that's what that line did. Thanks for your help!
