### ISSUE TITLE
why spector.js can't hook the frame from  tencent map ? 

### ISSUE THREAD

**Issue by adlovley** [BabylonJS/Spector.js#168]
here is the tencent map URL:
https://lbs.qq.com/webDemoCenter/glAPI/glMap/createMap

how did tencent prevent hook webgl ?

**Comment by sebavan** [comment]
It is because they rely on offscreenCanvas in a worker thread which is unfortunately not supported: #90

**Comment by adlovley** [comment]
thanks, I try it myself

**Comment by adlovley** [comment]
good,  That's true
