### ISSUE TITLE
Implement WEBGL_debug extension proposal

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#170]
This issue is about implementing the [WEBGL_debug extension proposal](https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_debug/) in spector.js.

I'm aware that the extension was only a proposal ("DO NOT IMPLEMENT!!!"), and it's old, too.
However, this API style is [common in other OpenGL variants](https://www.khronos.org/opengl/wiki/Debug_Output) (Core since OpenGL 4.3) and would help with having a standardized API that can also be used by other tools.
Application code ported from other OpenGL variants can also remain more standardized, too.

Hence, I believe that spector.js should inject this extension, and implement the interface described in the WEBGL_debug extension by wrapping its own debug functionality.

*(If anyone is aware why that extension never turned into a draft, feel free to respond with a veto)*

**Comment by sebavan** [comment]
Would you be willing to contribute the implementation ?

I am unfortunately not able to foresee a time where I could do it :-(

**Comment by JannikGM** [comment]
Yes, potentially some of it, if my employer allows me to spend time on it. Not a priority for me, though.
I'll only work on it if there's a chance of such a change being accepted (and therefore maintained by someone else).

**Comment by sebavan** [comment]
I could definitely help with the maintenance once integrated and happy to see those improvments.

**Comment by sebavan** [comment]
Closing as won t do as the proposal extension has been without acitivities
