### ISSUE TITLE
Need equivalent to glDebugMessageInsert

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#171]
I'm not sure if such a feature already exists, but I want to be able to add custom debug message strings in the GL command log. Basically a `console.log` on the `window.spector` API.

This would also be needed for #170 

*(This is a duplicate of https://github.com/BabylonJS/Spector.js/issues/154 which I only found after creating the issue; however, the original request still stands; it's impossible to have an debug mark / custom message, without also invoking some WebGL call)*

**Comment by sebavan** [comment]
Attach to https://github.com/BabylonJS/Spector.js/issues/170
