### ISSUE TITLE
Metadata display is disruptive

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#173]
I'm using `__SPECTOR_Metadata` on my buffers, but the output is very disruptive.

Unfortunately, the right pane isn't very structured to begin with (it doesn't *visually* layout group attributes / uniforms together, so you must read every headline).

However, the display of metadata just makes it way more difficult to read.

See the following example where the attribute entry is essentially split in 2 parts by the headlines blue horizontal-line.

It took me a while to realize that the `arrayType` was `UNSIGNED_BYTE` (in bottom-half, disconnected from upper half) and not `FLOAT_VEC4` (more prominently displayed as `type` in upper half)

![Screenshot 2021-01-28 at 13 29 46](https://user-images.githubusercontent.com/72194488/106139558-e23e5f00-616d-11eb-90d8-b58ec330cbb1.png)

The readability would probably be better if the "Metadata" headline didn't exist.

**Comment by sebavan** [comment]
See discussion on https://github.com/BabylonJS/Spector.js/issues/170

**Comment by sebavan** [comment]
Won t fix for now, would need a better display overall
