### ISSUE TITLE
Allow Metadata for shaders, programs and textures

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#174]
Currently, shaders can be named by the `SHADER_NAME` define. However, that makes it impossible to rename shaders, without also changing their source-code (which would be bad for performance).
Instead, it would be helpful if shaders could simply be labelled using `__SPECTOR_Metadata`, which already exists for other WebGL objects.

Programs can't seem to be named yet, but this might also be useful. Again, this should be possible through `__SPECTOR_Metadata`.

Textures *also* can't be named, but this would be a very useful feature (to display the filename, high-level API information, ...). Again, this should be possible through `__SPECTOR_Metadata`.

There might also be other, still unsupported, OpenGL object types where labeling through `__SPECTOR_Metadata` would be nice-to-have.

This would also be needed for #170 probably.

*(Also, while I'm here, there also seems to be a `__SPECTOR_Object_CustomData`; when is that to be used?)*

**Comment by sebavan** [comment]
See discussion on https://github.com/BabylonJS/Spector.js/issues/170

**Comment by sebavan** [comment]
__SPECTOR_Object_CustomData are internals to spector only. It is where the state is recorder on gl objects where introspection does not work.

**Comment by sebavan** [comment]
__SPECTOR_Metadata should be working fine on many objects including shader name from them as you can see in the metadata sample in the repo
