### ISSUE TITLE
Allow viewing of translated shader source

### ISSUE THREAD

**Issue by kenrussell** [BabylonJS/Spector.js#175]
SpectorJS' ability to view the vertex and fragment shader source for draw calls is very useful.

Could https://www.khronos.org/registry/webgl/extensions/WEBGL_debug_shaders/ please be integrated to allow viewing of the translated shader source that was fed to the graphics driver? This would allow debugging of issues in the browser much more easily - please see http://crbug.com/1164876 for one example.

Thanks. If you have any pointers in the code about how to hook this up, I could also give it a try.

**Comment by sebavan** [comment]
Yup, I guess it could be not to hard.

Let me give it a quick try over the week end :-)

**Comment by sebavan** [comment]
Closed by https://github.com/BabylonJS/Spector.js/commit/8ebe7d9cbbaf4c91a15d801eb657da764b3e88f0 This will be deployed as soon as the review process has been passed:

The shader tabs now includes the translated ones.

![image](https://user-images.githubusercontent.com/16655165/107282799-c6836480-6a5b-11eb-9ebc-899a322082df.png)

**Comment by kenrussell** [comment]
Thank you so much @sebavan for implementing this! Looking forward to the next SpectorJS update!

**Comment by sebavan** [comment]
No problem, least I could do ;-)
