### ISSUE TITLE
`fragment: false` / `fragment: true` on Shaders is confusing

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#179]
This should instead be something like `shaderType: GL_VERTEX_SHADER` and `shaderType: GL_FRAGMENT_SHADER` so it's more obvious.
That change would also tie it in with the https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/createShader API (note that Desktop OpenGL manpages calls the parameter `shaderType`)

**Comment by sebavan** [comment]
Feel free to make a PR if you want this one in, totally not opposed to it.

**Comment by sebavan** [comment]
Would you be willing to make a PR for it ?

**Comment by JannikGM** [comment]
I don't have time to work on this right now.

I've started moving away from custom WebGL code and primarily use existing engines / wrappers now, so I rarely have to debug WebGL directly at the moment. However, I'm sure this will change again eventually + I occasionally still debug WebGL.
So I'm still interested in seeing this fixed, but I can't devote any time to this right now.
