### ISSUE TITLE
Display bound ELEMENT_ARRAY_BUFFER

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#180]
I had a bug where my binding of `gl.ELEMENT_ARRAY_BUFFER` was modified by code in a third-party lib. This bug was hard to diagnose, and if the sidebar had information about the bound buffer, including the buffer object label, this could have been caught easily.

**Comment by sebavan** [comment]
Yup, this is missing let me see if I can easily add it.
