### ISSUE TITLE
Add option to disable spector.js hooks in browser extension

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#181]
Once I've started spector.js tracing by pressing the red icon of the extension, it will reload the page and turn green. Once it is green, the hooks are active and the performance is heavily degraded (which is fine, as it has the benefit of allowing to trace later).

However, there does not seem to be a way to get back to the red icon / unhooked state, without closing the tab / reloading the website in a new tab.

Holding the reload-page button in the Chrome browser gives the following options:
- Normal Reload
- Hard Reload
- Empty Cache and Hard Reload

None of these options will disable the hooks. I can't seem to find an option in the spector.js UI to disable the hooks either.

There should be an option to disable spector.js again (also disabling tracing in the same session), so performance returns to normal, without having to close the tab.

**Comment by sebavan** [comment]
Spector is hooking to deep and it is hard to cleanup without side effects or left over on every items.

It is way safer to reload the page to be sure any leftover is gone.

**Comment by JannikGM** [comment]
How to reload though? I can't seem to find out an option without closing the tab, which breaks other extensions / some debugger state

**Comment by sebavan** [comment]
ohhh I see maybe a unload button which would refresh the page without the hooks ?

**Comment by JannikGM** [comment]
> ohhh I see maybe a unload button which would refresh the page without the hooks ?

Yes, that'd probably already be "good enough".
Basic support like this would be an important feature for us.
