### ISSUE TITLE
Display command index

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#185]
There should be a way to see the draw call index and WebGL command index in the left pane, and there should be a WebGL command index in the center pane.

Such information is helpful for:

- The "[N] first commands" feature
- Talking to other developers when looking at traces together
- If a metric is to reduce the number of draw calls

**Comment by sebavan** [comment]
We already have the number of draw calls available so I am not to sure of this one. If you find it useful, I am totally not opposed to a PR, would you want to do it ? or I ll close it.
