### ISSUE TITLE
Spector failure（spector失效）

### ISSUE THREAD

**Issue by Jeggery** [BabylonJS/Spector.js#189]
I'm using spector.js to monitor WebGL pages. There is an error（我使用spector.js监测webgl页面，出现了一下错误）
![ddd](https://user-images.githubusercontent.com/39072827/111262748-b7499500-865f-11eb-8968-f6182a3a6d0c.png)
![ss](https://user-images.githubusercontent.com/39072827/111262754-ba448580-865f-11eb-85ba-5fdeceeeccaa.png)

**Comment by Jeggery** [comment]
I have attached a link here（我在此附上一个链接）
[https://www.hightopo.com/demo/airport-t3/](url)

**Comment by sebavan** [comment]
Hello I am not able to repro :-(

Despite being dead slow (23450 commands is a lot per frame) I can see the result by pressing please wait quite a few times:

![image](https://user-images.githubusercontent.com/16655165/111319062-eb27b900-8665-11eb-87c0-e12e5fa34c46.png)

I guess you might have other webgl extensions in conflict with spector ? you should try keeping only spector enable when doing the capture ?

**Comment by Jeggery** [comment]
Hello, I have turned off other monitoring procedures, the page crashed after waiting for a long time,（您好，我已经关掉其它的监测程序，等待很长时间后页面崩溃了）, Below is a screenshot of what I just tested(下面是我刚测试的截图)
![监测报错](https://user-images.githubusercontent.com/39072827/111400166-bb2df380-8701-11eb-81d3-7c2703ed0504.png)

**Comment by Jeggery** [comment]
> Hello I am not able to repro :-(
> 
> Despite being dead slow (23450 commands is a lot per frame) I can see the result by pressing please wait quite a few times:
> 
> ![image](https://user-images.githubusercontent.com/16655165/111319062-eb27b900-8665-11eb-87c0-e12e5fa34c46.png)
> 
> I guess you might have other webgl extensions in conflict with spector ? you should try keeping only spector enable when doing the capture ?

There are some pages I can monitor(对于有些页面我是可以监测的)，Such as（比如）
[https://www.hightopo.com/demo/city/](url)，
[https://www.hightopo.com/demo/ht-smart-building/index.html](url)，
Some pages cannot be monitored, Such as
[https://www.hightopo.com/demo/powerCiity/](url)，
[https://www.hightopo.com/demo/airport-t3/](url)，
This is a very strange thing to me（这对我来说是个很奇怪的事情），I wonder if there is any program on some pages that prevents spector.js from being monitored（我在想有些页面是否有什么程序阻止了spector.js的监测）,If that's the case, it's confusing（如果是那样，就很困惑了）。
Therefore, I would like to ask whether the WebGL of the web page can be monitored by using spector.js（因此我想问一句，对于网页的webgl是否都能使用spector.js去监测）
Thank you for your answer（谢谢解答）

> Hello I am not able to repro :-(
> 
> Despite being dead slow (23450 commands is a lot per frame) I can see the result by pressing please wait quite a few times:
> 
> ![image](https://user-images.githubusercontent.com/16655165/111319062-eb27b900-8665-11eb-87c0-e12e5fa34c46.png)
> 
> I guess you might have other webgl extensions in conflict with spector ? you should try keeping only spector enable when doing the capture ?
There are some pages I can monitor(对于有些页面我是可以监测的)，Such as（比如）
[https://www.hightopo.com/demo/city/](url)，
[https://www.hightopo.com/demo/ht-smart-building/index.html](url)，
Some pages cannot be monitored, Such as
[https://www.hightopo.com/demo/powerCiity/](url)，
[https://www.hightopo.com/demo/airport-t3/](url)，
This is a very strange thing to me（这对我来说是个很奇怪的事情），I wonder if there is any program on some pages that prevents spector.js from being monitored（我在想有些页面是否有什么程序阻止了spector.js的监测）,If that's the case, it's confusing（如果是那样，就很困惑了）。
Therefore, I would like to ask whether the WebGL of the web page can be monitored by using spector.js（因此我想问一句，对于网页的webgl是否都能使用spector.js去监测）
Thank you for your answer（谢谢解答）

**Comment by sebavan** [comment]
It should just work and on https://www.hightopo.com/demo/powerCiity/ I am able to capture :-(

But the capture is too big to transfer over so in your case you could limit how many  commands you are capturing with 
![image](https://user-images.githubusercontent.com/16655165/111514920-7ed6b380-8752-11eb-8247-5822527fb152.png)

set the number of commands and click capture or you could rely on the APIs to capture from some targeted places in your code.

**Comment by Jeggery** [comment]
> It should just work and on https://www.hightopo.com/demo/powerCiity/ I am able to capture :-(
> 
> But the capture is too big to transfer over so in your case you could limit how many commands you are capturing with
> ![image](https://user-images.githubusercontent.com/16655165/111514920-7ed6b380-8752-11eb-8247-5822527fb152.png)
> 
> set the number of commands and click capture or you could rely on the APIs to capture from some targeted places in your code.

I have been waiting on this page for a long time but still invalid, And I've set the number of catches to be small，It's so confusing
![spector等待2](https://user-images.githubusercontent.com/39072827/111564826-5cd24500-87d5-11eb-99ef-70743c174470.png)

**Comment by Jeggery** [comment]
> > 它应该可以正常工作，并且可以在https://www.hightopo.com/demo/powerCiity/上捕获到：-(
> > 但是捕获量太大而无法转移，因此在您的情况下，您可以限制捕获的命令数量
> > ![图像](https://user-images.githubusercontent.com/16655165/111514920-7ed6b380-8752-11eb-8247-5822527fb152.png)
> > 设置命令数量并单击捕获，或者您可以依靠API从代码中的某些目标位置捕获。
> 
> ![幽灵等待2](https://user-images.githubusercontent.com/39072827/111564826-5cd24500-87d5-11eb-99ef-70743c174470.png)

**Comment by sebavan** [comment]
I looks like you pressed the red button which capture the full frame being to big as mentionned previously.

could you try after chosing the number of command to press
![image](https://user-images.githubusercontent.com/16655165/111654050-b0aa5180-8808-11eb-9f79-0b589d612d53.png)

to ensure you only capture the selected number of commands ?

**Comment by Jeggery** [comment]
> I looks like you pressed the red button which capture the full frame being to big as mentionned previously.
> 
> could you try after chosing the number of command to press
> ![image](https://user-images.githubusercontent.com/16655165/111654050-b0aa5180-8808-11eb-9f79-0b589d612d53.png)
> 
> to ensure you only capture the selected number of commands ?

Just tried to change the number of commands, is OK。However, I found that the maximum number of catches after the change was 5000，For this page， [https://www.hightopo.com/demo/powerCiity/](url), Content capture for the entire web page is incomplete。
for this [https://www.hightopo.com/demo/airport-t3/](url), My browser captures around 2000，More than that and the page will crash, As shown in the figure below
![spector崩溃](https://user-images.githubusercontent.com/39072827/111721174-53f77700-889a-11eb-88ae-6d3d983cbf3f.png)
What causes this, and why can't more be caught。
![spector最初](https://user-images.githubusercontent.com/39072827/111721273-7db09e00-889a-11eb-9e19-68b811d977e2.png)
![spector最后](https://user-images.githubusercontent.com/39072827/111721282-830de880-889a-11eb-9e77-72280d6f1426.png)
The initial loading of the object captured in the Frame buffer on the left side of the first image is not very clear,
The second image has no images in its Frame buffer,What's the reason。
How can I capture all the quantities，What does the "command" mean?
Thank you for answering

**Comment by sebavan** [comment]
I can not repro 
![image](https://user-images.githubusercontent.com/16655165/111823826-b2961280-88e5-11eb-862c-4050210be2eb.png)

It looks like it is only related to your environment.

The only thing I see in this scene is that it is too big to be fully captured.

The quick capture not snapshoting texture is actually ok 
![image](https://user-images.githubusercontent.com/16655165/111823948-db1e0c80-88e5-11eb-866d-4f9d094a7d55.png)

**Comment by Jeggery** [comment]
Thank you, texture snapshot this allows me to capture some code，That sounds like a good idea to me. But I can't show every frame without pictures. Is there a solution to this problem

**Comment by Jeggery** [comment]
> I can not repro
> ![image](https://user-images.githubusercontent.com/16655165/111823826-b2961280-88e5-11eb-862c-4050210be2eb.png)
> 
> It looks like it is only related to your environment.
> 
> The only thing I see in this scene is that it is too big to be fully captured.
> 
> The quick capture not snapshoting texture is actually ok
> ![image](https://user-images.githubusercontent.com/16655165/111823948-db1e0c80-88e5-11eb-866d-4f9d094a7d55.png)

Thank you, texture snapshot this allows me to capture some code，That sounds like a good idea to me. But I can't show every frame without pictures. Is there a solution to this problem

**Comment by sebavan** [comment]
The lost context is probably meaning you do not have enough memory to hold the entire capture so despite trying on a bigger box I am not sure there is anything to do, or you can use the code based api and target only part of your frames as anyway 30 000 commands are totally not readable.

**Comment by Jeggery** [comment]
> The lost context is probably meaning you do not have enough memory to hold the entire capture so despite trying on a bigger box I am not sure there is anything to do, or you can use the code based api and target only part of your frames as anyway 30 000 commands are totally not readable.

I see. How about capturing the frame me want according to the API，Because there are too many commands

**Comment by sebavan** [comment]
This would be the same, as the memory would have the same issue and as mentioned previously the capture would not be readable anyway due to the large number of command.

The best is to startCapture from the API at a given point and stopCapture when you did the pass you want to analyze. This way you would not suffer from the memory issue not the readability one.

**Comment by Jeggery** [comment]
> This would be the same, as the memory would have the same issue and as mentioned previously the capture would not be readable anyway due to the large number of command.
> 
> The best is to startCapture from the API at a given point and stopCapture when you did the pass you want to analyze. This way you would not suffer from the memory issue not the readability one.

Thanks， Want to ask how to use the API to get, can you give an example

**Comment by sebavan** [comment]
You can use it as a script like this: https://github.com/BabylonJS/Spector.js/blob/master/readme.md#use-as-a-script-reference

with the following available APIs:

https://github.com/BabylonJS/Spector.js/blob/master/documentation/apis.md

**Comment by Jeggery** [comment]
> 您可以将其用作如下所示的脚本：[https](https://github.com/BabylonJS/Spector.js/blob/master/readme.md#use-as-a-script-reference) : [//github.com/BabylonJS/Spector.js/blob/master/readme.md#use-as-a-script-reference](https://github.com/BabylonJS/Spector.js/blob/master/readme.md#use-as-a-script-reference)
> 
> 具有以下可用的API：
> 
> https://github.com/BabylonJS/Spector.js/blob/master/documentation/apis.md

Thanks, I'll have a good look, Thank you for your answer
