### ISSUE TITLE
Chrome Extension Link is broken

### ISSUE THREAD

**Issue by BrunoWilkinson** [BabylonJS/Spector.js#190]
The current Chrome extension link hits an 404 Error.
(https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk)
![image](https://user-images.githubusercontent.com/14802661/112632784-7a845780-8e30-11eb-9779-7bca47628a78.png)

**Comment by sebavan** [comment]
Yup I am working on it, it has been removed from the store due to the tabs policy setting I am trying to workaround :-(

**Comment by sebavan** [comment]
During this time you can install it locally by importing the extension folder from the repo as a local extension.

**Comment by sebavan** [comment]
I hope it will be back next week

**Comment by BrunoWilkinson** [comment]
No problem! Wasn't sure if you guys were aware of it.

**Comment by sebavan** [comment]
All fixed by now :-)
