### ISSUE TITLE
Why canvas frame buffer Can't zoom in

### ISSUE THREAD

**Issue by kefeibuhuifei** [BabylonJS/Spector.js#197]

**Comment by kefeibuhuifei** [comment]
canvas frame buffer shi too small, I can't see the changes before and after

**Comment by JannikGM** [comment]
This is missing a whole lot of context. Please provide it (in the description of the issue), or this should be closed.

**Comment by sebavan** [comment]
yup would be great to detail a bit ?

**Comment by kefeibuhuifei** [comment]
I uploaded a picture and I want to see the details of this place

**Comment by JannikGM** [comment]
Use "Full Capture (real size textures: slow)" in Spector.js and the image will be captured full size.
The WebUI will still display it smaller; so you have to "Open image in new tab" in the right-click context menu (or similar, to get the image data).

**Comment by kefeibuhuifei** [comment]
> Use "  Full Capture (real size textures: slow)" in Spector.js capture settings and the image will be captured full size.
> The WebUI will still display it smaller; so you have to "Open image in new tab" in the right-click context menu (or similar, to get the image data).

thanks!!!

**Comment by sebavan** [comment]
Yup, this is the exact intent of this as it is usually dead slow we do not do it by default.
