### ISSUE TITLE
Viewing saved captures is broken on Chrome and Firefox

### ISSUE THREAD

**Issue by jparismorgan** [BabylonJS/Spector.js#199]
I can save data as JSON from iOS. But when I drag the JSON into the Chrome extension on Mac, nothing happens. It is perhaps because the area is cut off?

![Screen Shot 2021-06-07 at 4 56 50 PM](https://user-images.githubusercontent.com/1396242/121101775-5be7f880-c7b1-11eb-81c0-ebfb1a3118d6.png)

**Comment by sebavan** [comment]
sounds definitely like a bug... I can repro everywhere. In a workaround on the desktop app, do a capture on https://playground.babylonjs.com/ and in the captures list you can drag the json to open: 
![image](https://user-images.githubusercontent.com/16655165/121101976-2c5edd80-c7fd-11eb-85aa-05a47dbda68a.png)

I ll fix the main entry ASAP

**Comment by sebavan** [comment]
fixed in the latest commit
