### ISSUE TITLE
Seeing only the last frame with Chrome extension

### ISSUE THREAD

**Issue by liorGameDev** [BabylonJS/Spector.js#202]
We are using Spector.js in a react-three-fiber scene, And it is possible to see only the first few frames and the last frame buffer, but not all of the other frames buffers. Any ideas how can we watch them?

![image](https://user-images.githubusercontent.com/15868082/122721692-a53c4b80-d279-11eb-8722-95633e8143f7.png)

**Comment by sebavan** [comment]
The frame buffers are in this case not from a renderable type.

Do you have a repro to confirm ?

**Comment by liorGameDev** [comment]
@sebavan 
What makes you know that?
As it can be seen in the image, the last frame is created from several meshes, but it was not possible to see with the frames, the process that created it (For example which mesh was rendered before others)

**Comment by sebavan** [comment]
This is one of the only reason we would not capture a frame buffer. I might happen for a shadow map for instance. you could look into the frame buffer setup for the draw call to confirm
