### ISSUE TITLE
Shader name shown instead of shader source for Three.js applications

### ISSUE THREAD

**Issue by OndrejSpanel** [BabylonJS/Spector.js#206]
Here is what [documentation](http://www.realtimerendering.com/blog/debugging-webgl-with-spectorjs/) says about inspecting shaders:

> From this panel, the shader source code is also available from the program information, by following the Click to open link:

There is a picture illustrating what I should see:

![image](https://user-images.githubusercontent.com/6927223/133244721-a97c2e10-b7d8-44e1-987b-7a60e9008667.png)

And here is what I really see:

![image](https://user-images.githubusercontent.com/6927223/133244653-b428e681-3d3b-4198-b758-9131ec3b3cf4.png)

This is for my Three.js application, and I can see the same with Three.js examples. like https://threejs.org/examples/webgl_geometry_cube

- why is shader source not shown to me?
- what is the shader name I see? I do not see any `__SPECTOR_Metadata` or any mention to Spector in the Three.js sources

I see the issue was probably already discussed in #145, but I do not understand the resolution. Is the issue supposed to be fixed on Spector side, on Three.js side, or is it just a limitation I should learn to live with?

The Three.js revision I use is 131, and it does not use  `gl.detachShader` before calling `gl.deleteShader`.

**Comment by OndrejSpanel** [comment]
I think this is probably a documentation error. I can access in the render call:

![image](https://user-images.githubusercontent.com/6927223/133248010-4d17c249-c579-4af4-a800-7df4e9d95fe2.png)

Still, I am curious to know what is the name I am shown and how does Spector obtain it.

... and the documentation could be fixed to help unexperienced users like me.

**Comment by sebavan** [comment]
The name is extracted by introspecting the shader code and finding this kind of tag:
```
#define SHADER_NAME vertex:default
```

By convention we all use it. also if you try in Babylon.js you ll notice you can even edit the shaders in real time
