### ISSUE TITLE
Unexpected texture memory results

### ISSUE THREAD

**Issue by donmccurdy** [BabylonJS/Spector.js#207]
I'm loading these two textures one at a time in https://sandbox.babylonjs.com/ and trying to confirm the texture memory associated with each. It's the same texture in JPEG and KTX2 (UASTC) format, and I'd expected the memory use to be about 21 MB and 5 MB respectively.

[Archive.zip](https://github.com/BabylonJS/Spector.js/files/7212180/Archive.zip)

When I run the SpectorJS profile and check the Information -> Total Memory -> Texture2D section, I'm seeing a bit larger number for the KTX2 texture (18MB), and nothing at all for the JPEG texture: total memory is not shown.

**KTX2**

![Screen Shot 2021-09-22 at 8 56 01 AM](https://user-images.githubusercontent.com/1848368/134378973-8236125e-ae48-4bbf-b97a-ff1b582fc56f.png)

Is this expected? I'm trying to help debug a larger application for a three.js user, and they're seeing higher memory reported with Basis UASTC which doesn't seem right, so I'm wondering if this could be related.

**Comment by sebavan** [comment]
So if you drag them one after the other I am seeing:

![image](https://user-images.githubusercontent.com/16655165/134406670-b56e5522-2666-4567-b8c4-3a0dbdcd487e.png)

or 

![image](https://user-images.githubusercontent.com/16655165/134406709-2d082a03-1250-4c41-a98a-d45e6ec9feb7.png)

Those numbers are representing the total amount of texture memory at some points in time.

the numbers are coming from here https://github.com/BabylonJS/Spector.js/commit/97c992dc99b75a43d2a73e60ba9fefbb60028e1c and they are totally inaccurate for compressed textures I guess... I think it should only be the size of the buffer here ?

**Comment by donmccurdy** [comment]
I'm seeing something a bit different but similar, starting with the KTX texture and then the JPEG. Possibly coming down to browser (Firefox) and hardware differences? I'm not sure whether mipmaps are generated.

- **12:** 18087936
- **17:** 13893632

I think you're correct that the size of the buffer is the right thing to show for compressed textures. I've written [some code in gltf-transform](https://github.com/donmccurdy/glTF-Transform/blob/a07b4df67a1cb252f12025754eadc4db5af82212/packages/extensions/src/khr-texture-basisu/texture-basisu.ts#L28-L48) to estimate memory from the source KTX2 file, but it makes assumptions about what the transcode target is going to be, whereas using the transcoded buffer size should be precise.

**Comment by sebavan** [comment]
Yup, I ll try to fix it by end of week. Thanks for reporting it !!!

**Comment by sebavan** [comment]
Ok with my current changes: #208 I can now see:

![image](https://user-images.githubusercontent.com/16655165/134427526-85fb80fa-b5e5-4100-8cb7-f3a8c4fb7b45.png)

and 

![image](https://user-images.githubusercontent.com/16655165/134427544-cfe4a08d-055d-4d9c-840f-439e76ad150f.png)

So which does looks better :-) could you confirm ?

**Comment by donmccurdy** [comment]
That's in the ballpark I'd expect if it's saying 7.9 MB for Basis Universal UASTC and 16.3 MB for JPEG. 

For KTX2 — do you happen to know if your hardware supports ASTC? If so, I'd have expected a somewhat lower number here. For anything else, [transcoded size varies](https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md#gpu-api-support).

For JPEG — those numbers sound like you're assuming 3 bytes per pixel. I tend to estimate as if RGB will be expanded to RGBA in memory, based on https://github.com/donmccurdy/glTF-Transform/issues/151#issue-769158235. Not sure if that can be detected from JS; can't fault Spector.js one way or another if not. 😄

**Comment by sebavan** [comment]
About KTX2 👍 
![image](https://user-images.githubusercontent.com/16655165/134441592-1d2a3d9c-d180-45e6-a852-ab2afd5804cd.png)

For JPEG, is it only JPEG or any RGB texImage... calls which would expand ??? (this is so hardware dependant that I am wondering which one to pick, but knowing Spector is mostly a desktop usage maybe I should infer differently)

**Comment by sebavan** [comment]
fixed by #208

**Comment by donmccurdy** [comment]
I would have guessed it was any RGB uncompressed image, but I don't really know. (/cc @lexaknyazev might?)

In any case, thanks for the quick fix here! ☺️

**Comment by lexaknyazev** [comment]
> For JPEG, is it only JPEG or any RGB texImage... calls which would expand ???

Direct3D and Metal do not even support RGB8 pixels, so such textures are always expanded to RGBA8 when running WebGL on top of these platforms. The situation is slightly different with other APIs:
- On Vulkan, it's explicitly optional. So in case of WebGL, the translation layer does the expansion if needed. 
- On OpenGL, it's hardware-dependent and happens silently in the driver.

**Comment by sebavan** [comment]
Thanks a lot, I ll try to change it ASAP
