### ISSUE TITLE
`scissor` calls are marked as redundant, despite scissor-region being modified

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#215]
My code is basically this:

```js
gl.enable(GL.SCISSOR_TEST);
for(let x = 0; x < 10; x++) {
  gl.scissor(x * 10, 0, 8, 8);
  gl.clearStencil(x);
  gl.clear(GL.STENCIL_BUFFER_BIT);
}
```

Each of the `scissor` calls is being marked as redundant. There's no explicit list of redundant command IDs.
The scissor affects the clear and the parameters are different each time, so there's no reason why this should be redundant?

**Comment by sebavan** [comment]
I ll have a look this weekend, I am pretty sure the state does not account for the provided size info in some ways
