### ISSUE TITLE
Erroneous guess about GL constants in bindAttribLocation index parameter

### ISSUE THREAD

**Issue by monfera** [BabylonJS/Spector.js#220]
![image](https://user-images.githubusercontent.com/1548516/148458279-783312d0-cc04-49c8-a24d-b39431fb0acf.png)

Instead of numbers, values 2...6 are shown as GL primitives, rather than numbers

**Comment by JannikGM** [comment]
The generic solution is to find the first matching enum for a number (but that is often incorrect).
You'll have to add explicit stringification similar to https://github.com/BabylonJS/Spector.js/pull/212

Another solution could be to improve the stringifaction to only become active for `GLenum`

**Comment by sebavan** [comment]
> Another solution could be to improve the stringifaction to only become active for `GLenum`

This would be great indeed, would you mind doing a PR for it, or I ll add the targeted fix over the weekend ?
