### ISSUE TITLE
Support SRGB8_ALPHA8 textures

### ISSUE THREAD

**Issue by 0b5vr** [BabylonJS/Spector.js#225]
### Description

It would be nice to have a preview of SRGB8_ALPHA8/EXT_sRGB textures.
It's currently not shown on uniforms inspector.
If it's not easily achievable, I want to see the textureType - height section in the screenshot below at least.

### Screenshots

texture with internalformat: RGBA8

![texture with internalformat: RGBA8](https://user-images.githubusercontent.com/7824814/150932452-aa40a371-8e8b-40b5-882d-2e877d8057e8.png)

texture with internalformat: SRGB8_ALPHA8

![texture with internalformat: SRGB8_ALPHA8](https://user-images.githubusercontent.com/7824814/150932506-10ce4500-6925-4a5d-bab5-c618472d632f.png)

### Motivation

Since Three.js r133, it starts using SRGB8_ALPHA8 textures and most of color textures are encoded using SRGB8_ALPHA8, which can't be seen via Spector.js currently.

https://github.com/mrdoob/three.js/pull/22551

### Unrelated

Spector.js saves my life many times so far, thank you for your work :pray:

**Comment by sebavan** [comment]
Would be great indeed and should not be to hard to add :-) Would you have a quick repro page I can use to try it out ?

**Comment by 0b5vr** [comment]
This one must be simple enough for example:

https://threejs.org/examples/webgl_materials_normalmap.html

**Comment by sebavan** [comment]
Thanks, I ll have a look ASAP

**Comment by sebavan** [comment]
I ll have a look tonight sorry for the delay thanks for the repro.

**Comment by sebavan** [comment]
So it is currently working in Babylon 
![image](https://user-images.githubusercontent.com/16655165/155606124-0eadfbdb-4df8-4d2e-8920-0d240b8fbfd6.png)

Here the issue is spector seems to not catch the texture setup required info to render.

The way it is recorded is through either one of ("texImage2D", "compressedTexImage2D", "texStorage2D")

**Comment by sebavan** [comment]
looks like three is using texSubImage2D which we are not supporting so far to detect texture info, I ll see if I can add it

**Comment by sebavan** [comment]
This sounds to be the exact same issue than #227

**Comment by 0b5vr** [comment]
I confirmed it's now previewing sRGB textures on my end.
However the color output does not respect the sRGB EOTF.
I believe it will need an expensive CPU-side conversion, so that's not a priority task I think.
Thank you for your work!

**Comment by 0b5vr** [comment]
ahh that was an issue about texStorage2D, should have investigated that depth.
