### ISSUE TITLE
Triangle Count is actually Indices Count

### ISSUE THREAD

**Issue by Squareys** [BabylonJS/Spector.js#232]
Hi all,

I just got a report that rendering two planes (two triangles each) produces the following statistics in Spector.js:
![image](https://user-images.githubusercontent.com/1889284/170009460-d95ba82c-d780-4d4b-b106-5b24bebb7fe1.png)

It seems that in https://github.com/BabylonJS/Spector.js/blob/767ad1195a25b85a85c381f400eb50a979239eca/src/backend/analysers/primitivesAnalyser.ts#L74

The count is forwarded as-is to the primitive counts, but every call to this function will just forward the "count" argument, e.g. of [glDrawArrays](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/drawArrays), which is actually the index count.

Solution would be to divide the count by primitive size everywhere.

Best,
Jonathan

**Comment by Squareys** [comment]
Maybe make the title of the list "Vertex Counts" (or Index Counts) rather than "Primitives"? I think that could avoid the confusion 👍

**Comment by marquizzo** [comment]
Do you know if this fix will be available for the Firefox add-on? The Firefox store says the add-on was [last updated on Jan 4th, 2021.](https://addons.mozilla.org/en-US/firefox/addon/spector-js/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by sebavan** [comment]
You are totally right :-( I will update both chromium and mozilla assets as soon as I can (should be done by next week max if the process did not change too much)

**Comment by sebavan** [comment]
Both Chrome and Firefox are in verification process as we speak :-)
