### ISSUE TITLE
How to download to get the full mapping？

### ISSUE THREAD

**Issue by KaWah1222** [BabylonJS/Spector.js#234]
It seems to miss part of the mapping, and I don't know how to fix it.
![image](https://user-images.githubusercontent.com/51141646/170808444-0b5bd8c2-a220-4806-9aec-03e0acaba4f5.png)
![image](https://user-images.githubusercontent.com/51141646/170808447-a373d61c-6984-4c91-8daf-f4487b63da08.png)

**Comment by sebavan** [comment]
I am not sure what you mean ?
