### ISSUE TITLE
not work on shadertoy website

### ISSUE THREAD

**Issue by ligaofeng0901** [BabylonJS/Spector.js#235]
https://www.shadertoy.com/
The Chrome extension can't detect any frame.

**Comment by sebavan** [comment]
So you first need to select which canvas you work with:

![image](https://user-images.githubusercontent.com/16655165/173914795-da0d0872-d177-4dce-890d-ca08446081f7.png)

Then select the amount of commands as not relying on RAF and click the capture like:

![image](https://user-images.githubusercontent.com/16655165/173914941-7b9f2773-629c-4822-bee2-f8676cc95086.png)

and it should be ok:

![image](https://user-images.githubusercontent.com/16655165/173915034-6c7f8314-0d47-4651-b691-af8835891c46.png)
