### ISSUE TITLE
Using SpectorJS on mobile devices

### ISSUE THREAD

**Issue by sanjeetsuhag** [BabylonJS/Spector.js#239]
Is there a recommended way of using SpectorJS on Android, for example? I can use something like the [Kiwi browser](https://kiwibrowser.com/) to install SpectorJS, however, I cannot get it to select a canvas to record on.

Is the best option to integrate the SpectorJS API into your application and somehow save the data to view on a desktop browser?

**Comment by sebavan** [comment]
Closing as dupplicate of https://github.com/BabylonJS/Spector.js/issues/79
