### ISSUE TITLE
Extension icon not appearing in Firefox

### ISSUE THREAD

**Issue by pfarnach** [BabylonJS/Spector.js#240]
I must be missing something obvious but I don't see the toolbar extension icon in Firefox and therefore can't use the extension. I've confirmed the the extension is installed (uninstalled and reinstalled it) and verified it's enabled in the Add-ons Manager. It does not appear in the Customize Toolbar menu where you'd normally add unpinned extensions. I was able to install and use the Chrome extension on the same target website without issue.

**Comment by sebavan** [comment]
ohhhhhh let me have a look ASAP

**Comment by sebavan** [comment]
seems to be working for me 
![image](https://user-images.githubusercontent.com/16655165/184672525-0350d3ab-4ed1-4369-8625-44c8b4966df8.png)

Let me try to uninstall reinstall the extension

**Comment by pfarnach** [comment]
Yup, I knew I was being dumb. The icon is inside the URL bar and not next to the other extension icons (why is that?), so I missed it. Thanks.

**Comment by sebavan** [comment]
> why is that?

I needed some functionalities shared across chrome an Firefox and this seems to be the only way to control icon styles and such from within the extension :-)

**Comment by pfarnach** [comment]
Gotcha, thanks again for your help!

**Comment by Trass3r** [comment]
Same here, I was already freaking out why the extension icon didn't turn green or anything, even after restarting etc.
