### ISSUE TITLE
can we have a button to go to capture results so far?

### ISSUE THREAD

**Issue by makc** [BabylonJS/Spector.js#243]
if I just pause the capture it only allows me to resume but not to see the results, until the number of commands is reached. this is not really working well for me when these commands are not running non-stop at 60 fps

**Comment by sebavan** [comment]
You should rely on the api to capture in this case. 

If you are not in a setInterval, requestAnimationFrame or similar, there is no way for the tool to understand what the notion of a frame is.

Sharing a repro would help to find the best alternative .

**Comment by sebavan** [comment]
closing for now, will reopen once we have a repro

**Comment by makc** [comment]
@sebavan youre right though that the issue is not about insufficient number of commands, I just tried to do the same thing in jsfiddle and pausing worked (as in: showed me the results). so I guess there was something app-specific that threw it off.
