### ISSUE TITLE
Chrome Console: Warning invalid enum value of type PredefinedColorSpace

### ISSUE THREAD

**Issue by kinglycodes** [BabylonJS/Spector.js#246]
Installed the chrome extension today from the actual repo.
When I inpsect a THREE.js scene I get this warning:

`The provided value 'function(){var t=c.now,n=y.executeOriginFunction(e.spiedCommandRunningContext,e.spiedCommandName,arguments),i=c.now,r={name:e.spiedCommandName,arguments,result:n,startTime:t,endTime:i};return e.callback(e,r),n}' is not a valid enum value of type PredefinedColorSpace.`

The warning seems to come for every object I have in the scene.
I don't want to disable all warnings completely.

How can I get rid of this warning?

**Comment by sebavan** [comment]
Thanks a lot for reporting !!!
