### ISSUE TITLE
Extension not working on my site

### ISSUE THREAD

**Issue by dyn-do** [BabylonJS/Spector.js#247]
I made the following site with Three.js.
However, even if I run this with Chrome extension, `result.html` is not displayed.
What am I missing?
https://vrm-test-stmy.vercel.app/

The Extension worked in the Three.js demo below.
https://threejs.org/examples/webgl_animation_skinning_additive_blending.html

**Comment by sebavan** [comment]
I am seeing some exceptions in the console and my guess is that they prevent the capture to work, also your app looks like it load with error 500 and such quite often. Do you have a stable repro without exceptions ?

**Comment by sebavan** [comment]
Your app is clearing the page body somehow so everything related to spector is gone :-) you should prevent your app to clear document.body

**Comment by dyn-do** [comment]
@sebavan 
Thank you for confirming.
Since we're building pages with Sveltekit, the DOM is all built dynamically in JS.
It's a bit of a pain to stop using Sveltekit, but I'll give it a try without dynamic generation.

**Comment by dyn-do** [comment]
@dyn-do 
I got it to work by using Javascript modules instead of Chrome extensions.

**Comment by Popov72** [comment]
It does work for me if I click on "Transient" then on "Reload":

![image](https://user-images.githubusercontent.com/4152247/205434360-96b4fd48-9c59-4439-b5f1-d968c3e62759.png)
