### ISSUE TITLE
Spector does not capture images of our app

### ISSUE THREAD

**Issue by wdanilo** [BabylonJS/Spector.js#251]
Hi, I installed Spector by using `npm install spectorjs`, and I'm using it as:

```js
var SPECTOR = require("spectorjs");

var spector = new SPECTOR.Spector();
spector.displayUI();
```

After opening my app, I can see:
<img width="455" alt="CleanShot 2023-01-23 at 07 17 57@2x" src="https://user-images.githubusercontent.com/1623053/213976771-3707bbb1-c9bf-42ef-a310-57e1c5545af5.png">

So far, everything is OK. I can chose the canvas:
<img width="437" alt="CleanShot 2023-01-23 at 07 18 25@2x" src="https://user-images.githubusercontent.com/1623053/213976827-2afaa31a-91b3-4ecc-8731-2316be4e4309.png">

However, after clicking the red button, the images do not show up and I can see an icon of a broken image in the "captures" tab:

<img width="1342" alt="CleanShot 2023-01-23 at 07 18 59@2x" src="https://user-images.githubusercontent.com/1623053/213976885-e2406972-a97a-4aca-9917-6b5e5f09ae7d.png">

<img width="906" alt="CleanShot 2023-01-23 at 07 19 11@2x" src="https://user-images.githubusercontent.com/1623053/213976914-9df4b1cc-6766-4565-800a-69f89a3c5c61.png">

Would anyone be so nice and help me debug it / make it run correctly? :)

**Comment by sebavan** [comment]
This can certainly not capture the type of frame buffer (mainly related to the texture inside) you are using.

Only RGB/RGBA types with 8/16/32 bits are supported IIRC

We would need a repro to investigate further unfortunately, closing until we get more info mostly for house keeping but we can continue the discussion
