### ISSUE TITLE
multiDrawElementsInstancedWEBGL isnt spied 

### ISSUE THREAD

**Issue by Samsy** [BabylonJS/Spector.js#253]
multiDrawElementsInstancedWEBGL isnt spied on.

Checked the sources, it should be though !

But not showing up in spector !

Used both extension from chrome extension and unpacked souces as an extension also

**Comment by sebavan** [comment]
> Checked the sources, it should be though !
> 
> But not showing up in spector !

It is open source :-) Do you want to add it ? or at least provide a repro case ?

**Comment by Samsy** [comment]
I did meant to be mean of course ! Was just wondering if the current implementation was looking into that command, it look like it is from the sources, but does not look to work

Yes of course ! I will provide a repro case !

**Comment by sebavan** [comment]
No Worries, if you have a repro, I am game to add it in as it is not implemented so far.
