### ISSUE TITLE
Misleading translation of non-GLenum numbers to enum names

### ISSUE THREAD

**Issue by lazarljubenovic** [BabylonJS/Spector.js#262]
My code is using the following `bufferSubData` signature.

```
bufferSubData(target: GLenum, dstByteOffset: GLintptr, srcData: ArrayBufferView, srcOffset: GLuint, length?: GLuint): void;
```

I supply the optional `length` parameter as well.

This is what I see in Spector. The number of arguments is correct, but the last argument is very suspicious.

![image](https://github.com/BabylonJS/Spector.js/assets/7661457/3e973bb8-3a50-4100-8da2-6facc255513d)

Turns out that the `STENCIL_BUFFER_BIT` is the name of the GL constant defined like this.

```
readonly STENCIL_BUFFER_BIT: 0x00000400;
```

When you translate `0x400` to decimal, you get `1024` which is the actual value I'm passing as the `length` argument. It should just say `1024` instead of `STENCIL_BUFFER_BIT`.

(The `[object DataView]` is another weird thing visible on the screenshot, but I've opened a separate issue for this at #263.)

**Comment by sebavan** [comment]
Thanks for the report I ll address it over the weekend.

**Comment by sebavan** [comment]
Do you have a simple repro I can use to test ?

**Comment by lazarljubenovic** [comment]
Sorry, it's all based on a mess of a prototype for a library that I'm constantly changing and fiddling around with. I don't have anything at hand. It's pretty consistent though so any spot you have with `bufferSubData` can easily be changed to reproduce this.

**Comment by lazarljubenovic** [comment]
![image](https://github.com/BabylonJS/Spector.js/assets/7661457/1769d177-7671-4793-9bbf-40e2f4eb438e)

It's happening here too. The location should be printed as just a number, not as the name of the enum. [LINE_LOOP simply happens to be 2 and LINE_STRIP simply happens to be 3.](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Constants#rendering_primitives)
