### ISSUE TITLE
DataView displayed as [object DataView] instead of showing how many bytes were uploaded (bufferData, bufferSubData)

### ISSUE THREAD

**Issue by lazarljubenovic** [BabylonJS/Spector.js#263]
My code is using the following `bufferSubData` signature.

```
bufferSubData(target: GLenum, dstByteOffset: GLintptr, srcData: ArrayBufferView, srcOffset: GLuint, length?: GLuint): void;
```

Notice that it doesn't support passing in an `ArrayBuffer`, but only `DataView` or any of the concrete `TypedArray` classes. I am using a `DataView`.

This is what I see in Spector.

![image](https://github.com/BabylonJS/Spector.js/assets/7661457/3e973bb8-3a50-4100-8da2-6facc255513d)

The issue `[object DataView]`. It looks like an unhandled case which falls back to using a string for the report.

If you use a concrete `TypeArray` such as `Float32Array`, it tells me how much bytes were uploaded.

![image](https://github.com/BabylonJS/Spector.js/assets/7661457/a149bc9a-8f51-4725-963e-24f5d7bde8e2)

Similar thing happens to `bufferData` when you use a `DataView` instead of an `ArrayBuffer` or a concrete `TypedArray`.

![image](https://github.com/BabylonJS/Spector.js/assets/7661457/aaf3a32c-63db-4c45-bf85-67d9276e4ab1)

(The `STENCIL_BUFFER_BIT` is another weird thing visible on the screenshot, but I filed that as a separate issue as #262.)

**Comment by sebavan** [comment]
Thanks for the report I ll address it over the weekend.

**Comment by sebavan** [comment]
Do you have a simple repro I can use to test ?
