### ISSUE TITLE
CDN version is not up to date

### ISSUE THREAD

**Issue by De-Panther** [BabylonJS/Spector.js#264]
The content of the file in the CDN URL linked from the readme file is not up to date.
https://spectorcdn.babylonjs.com/spector.bundle.js
https://github.com/BabylonJS/Spector.js/blob/6afdc99115ffc4e20eb6253561dc8a75504de418/readme.md?plain=1#L115
It's missing lots of methods, including `Spector.log()` which seems to be added more than a year ago.

Is there another CDN URL?
Should we update the link to use a service like UNPKG? https://unpkg.com/spectorjs/dist/spector.bundle.js

**Comment by sebavan** [comment]
ohhh let me try to deploy it.

**Comment by sebavan** [comment]
should be ok now ? let me know if not. A change in the CD pipeline made it failed to deploy, thanks for reporting.
