### ISSUE TITLE
Source-code beautify `#if` indenting does not respect comments

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#270]
`_indentIfdef` doesn't check if the preprocessor is at the start of the line or in a comment, so even a line with a comment containing `#if` will mess up the indentation:

input:
```glsl
/* #if */
/* #if */
/* #if */
/* #if */
/* #if */
```

output:
```glsl
    /* #if */
        /* #if */
            /* #if */
                /* #if */
                    /* #if */
```

**Comment by sebavan** [comment]
I would say #269 is the best workaround for it as it is hard to figure whether the tokens are in comments or not.

Would be great to have a fully fledged beautifier :-)

**Comment by sebavan** [comment]
closing in favor of #283

Spector has never been thought as a tool to help during shader development and it would be great to enhance this area.
