### ISSUE TITLE
not work in https://www.capcut.cn/

### ISSUE THREAD

**Issue by x-wink** [BabylonJS/Spector.js#271]
can't get canvases list

**Comment by sebavan** [comment]
It is because they are dynamic. you need to check Show offscreen:

![image](https://github.com/BabylonJS/Spector.js/assets/16655165/de8bdec9-a534-4c38-a8bc-7781002ba2ba)

**Comment by x-wink** [comment]
Did you try to capture?
I got an error when checked `show offscreen canvas` like this:
No frames detected. Try moving the camera or implementing requestAnimationFrame.
the really canvas size not 300*150 and has id，it not exists in ext's canvases list.

**Comment by sebavan** [comment]
Is your app using a setInterval/requestAnimationFrame call to render ? And How/Where is your canvas ?

**Comment by x-wink** [comment]
sry I don't known,is not my app.
I just want to look for some beautful shader code.

**Comment by x-wink** [comment]
![image](https://github.com/BabylonJS/Spector.js/assets/133745023/b59d54b2-5edd-46d2-b145-f17e9d3a929f)

**Comment by sebavan** [comment]
It might be because they render offscreen and spector could not detect the canvas
