### ISSUE TITLE
Element sizes for the source-code view are partially hardcoded in CSS (layout needs refactor)

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#273]
While working on #272 I noticed that some of the CSS is hardcoded in pixel sizes and the layout depends on absolute element positioning.

Someone should redesign the Spector.js UI with proper CSS, rather than hardcoding the layout; current problems:

- The existing shader code UI breaks (= buttons become invisible, without any warning to the user) if there's not enough room for all buttons in the shader view (rather than tiny buttons or the dropdown menu), even if there's a reasonable amount of screen space (where I'd expect the UI to continue to function).
- The current dropdown menu for the main menu (at small screen sizes) is worse than representing these functions with smaller icons.
- The 3-pane design doesn't allow custom resizing of the 3 sections, even though this is probably beneficial.

**Comment by sebavan** [comment]
Closing this one as I do not think we will ever fix it.

I would gladly accept a React or any other modern framework based remake of the view :-)
