### ISSUE TITLE
`gl.shaderSource` is disruptive and doesn't provide enough information

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#278]
I have a long (generated) shader and it fails to compile. I'd like to review the shader source. Some observations:

- `shaderSource` in Spector.js is very long and it's easy to miss other commands inbetween 2 `shaderSource` which are huge blocks. The `shaderSource` log entry should be more minimalistic and show less information.
- The actual argument to `shaderSource` is not shown in the log, it's trimmed by "..." so I can't see the complete shader. Ideally, I'd like to open it in the shader editor, just like a shader during draw operations.
- The actual argument to `shaderSource` is not shown in the sidebar "Command Arguments" only has `0: WebGLShader - ID: 1` & `1: Array Length: 21858` which isn't very helpful because I still can't review the code.

**Comment by sebavan** [comment]
closing in favor of #283

Spector has never been thought as a tool to help during shader development and it would be great to enhance this area.
