### ISSUE TITLE
Show GLSL errors / warnings in the shader editor

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#279]
There should be an option to display GLSL errors and warnings in the editor.
Ideally, this would be shown in the respective lines.

The underlying editor supports this: https://mkslanc.github.io/ace-playground/#providing-custom-annotations
There's also some parser for GLSL errors / warnings in luma.gl that could be repurposed.

This is especially relevant after fixing #278; ideally, `gl.getShaderInfoLog` or `gl.compileShader` (and respective `gl.linkProgram` etc.) would also allow to jump to the editor (which could include said annotations).

**Comment by sebavan** [comment]
closing in favor of #283

Spector has never been thought as a tool to help during shader development and it would be great to enhance this area.
