### ISSUE TITLE
Show GL errors

### ISSUE THREAD

**Issue by JannikGM** [BabylonJS/Spector.js#280]
I realized some of my code causes `gl.INVALID_OPERATION`. I don't think this is currently revealed in Spector.js:

- No information in call log
- No information in sidebar (also no return value information!)

**Comment by sebavan** [comment]
As mentioned in the linked draft:

I honestly never though of Spector to troubleshoot those kind of errors as most of the info are only available in browsers console. There are no ways to access them.

This would only provide a tiny subset of the errors at the expense of a huge perf hit plus modifying the app flow by consuming the error on our side which might have weird unexpected side effects with the app which can think it is all good.

Closing for now but feel free to reopen if you have a magic trick to get the errors without impacting the app.
