### ISSUE TITLE
Uncaught ReferenceError: XRWebGLBinding is not defined in firefox 116.0.3  linux

### ISSUE THREAD

**Issue by riccardobl** [BabylonJS/Spector.js#286]
I am getting this error when trying to use spector.js on firefox  116.0.3  in Ubuntu 22.04.3 LTS
```
Uncaught ReferenceError: XRWebGLBinding is not defined
    107 https://spectorcdn.babylonjs.com/spector.bundle.js:76
    n https://spectorcdn.babylonjs.com/spector.bundle.js:76
    <anonymous> https://spectorcdn.babylonjs.com/spector.bundle.js:76
    <anonymous> https://spectorcdn.babylonjs.com/spector.bundle.js:76
    <anonymous> https://spectorcdn.babylonjs.com/spector.bundle.js:1
    <anonymous> https://spectorcdn.babylonjs.com/spector.bundle.js:1
```

To confirm the issue i've tested the official demo: https://spector.babylonjs.com/demos/pbr/
Everything works as expected with chrome on the same machine.

**Comment by sebavan** [comment]
Should have been fixed by https://github.com/BabylonJS/Spector.js/pull/285 let me try to deploy.

**Comment by sebavan** [comment]
Looks like it is all working back. Closing for now. Thanks for the report.
