### ISSUE TITLE
Consider supporting ASTC compressed textures?

### ISSUE THREAD

**Issue by catdoc** [BabylonJS/Spector.js#288]
Currently ASTC compressed textures seem not to be displayed.

**Comment by sebavan** [comment]
Yes, it is intended despite being frustrating.

We are only displaying the texture we can directly read the data from. Compressed textures as well as other none renderable/readable formats would require extra draw to render in RGBA textures and so on which could potentially break the current gl state and I am trying to minimize the impact of spector on the target application :-(

I am closing for now but I have to admit It would be amazing to have :-)
