### ISSUE TITLE
Save mesh to file?

### ISSUE THREAD

**Issue by barabanus** [BabylonJS/Spector.js#294]
Dear developers,

It would be truly helpful to have a possibility to store GL draw calls into a mesh file. Could you please support this feature?

**Comment by sebavan** [comment]
This has been asked several times but we unfortunately did not add it to prevent “stealing” rendering from other experience in a way to be sure spector is not banned by websites. You can use tags to troubleshoot tour own experience and be sure of which buffer is in use

**Comment by barabanus** [comment]
@sebavan Oh, I do understand your point!

Ok, what about saving raw buffers? Definitely, raw buffers are not enough to "steal" meshes without deep knowledge of what's going on internally

**Comment by sebavan** [comment]
Unfortunately, it was considered pretty similar at some point :-(

If it is to troubleshoot, you could probably rely on Spector tags instead ?

**Comment by barabanus** [comment]
@sebavan Technically, it's a flaw of the tool: why intrusively use external calls of the third-party library when this information is already available from a black box perspective. But your concern is understandable too, though there's a conceptual gap between raw buffers content and open mesh formats
