### ISSUE TITLE
Model won't load on chrome, addon greyed out and unclickable in firefox

### ISSUE THREAD

**Issue by SavantSusi** [BabylonJS/Spector.js#305]
Can't use it, chrome loads the model indefinitely and firefox greys out the addon and won't let me click on it

![Screenshot_20240428_124937](https://github.com/BabylonJS/Spector.js/assets/58572654/dc8ee92f-804a-485b-9c61-079b8f3f024b)

![Screenshot_20240428_124739](https://github.com/BabylonJS/Spector.js/assets/58572654/87be585c-b378-4580-abc8-9b3bbab41c31)

**Comment by lesbaa** [comment]
@SavantSusi Did you manage to resolve this issue? I'm still running into this.
