### ISSUE TITLE
Compressed texture cannot be displayed

### ISSUE THREAD

**Issue by Jeggery** [BabylonJS/Spector.js#306]
The detection of compressed texture cannot be displayed on the page.
For example, this page uses ktx texture:
[https://threejs.org/examples/webgl_loader_texture_ktx.html](url)

![compress](https://github.com/BabylonJS/Spector.js/assets/39072827/b8b65832-dd61-4ba5-9e80-3b02ff211626)

**Comment by sebavan** [comment]
We can not read them easily and it would require to interject a special render pass to copy them into another texture which is to risky as it would change a lot of states in the context.
