### ISSUE TITLE
Calling canvas.getContext("bitmaprenderer") with spectorjs plugin enabled causes error.

### ISSUE THREAD

**Issue by jaroslavbasista** [BabylonJS/Spector.js#307]
`let r = canvas.getContext("bitmaprenderer");`
Console shows error - **Uncaught TypeError: e.context.createFramebuffer is not a function.**

**Comment by sebavan** [comment]
Ohhhhh I ll see to fix it ASAP.

**Comment by sebavan** [comment]
@jaroslavbasista Do you have a repro page ? I can not seem to be able to repro :-(

**Comment by jaroslavbasista** [comment]
https://jsfiddle.net/ouwe1q74/1/

I get the error with the browser extension.

**Comment by sebavan** [comment]
Ohhhh once enabled in a page with webgl... makes sense sorry for asking. I ll see to fix it now
