### ISSUE TITLE
Warning in Chrome

### ISSUE THREAD

**Issue by rotu** [BabylonJS/Spector.js#312]
Google Chrome (129.0.6668.90) shows a warning about this extension:

> This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

And presents a link to this page: https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions

I believe this is because the extension uses Manifest V2: https://github.com/BabylonJS/Spector.js/blob/4a851022af887254a70bcf88a02cf074d89b4895/extensions/manifest.json

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Spector.js/commit/a02b152b7f711173bd175892fe4ca01e4015c4cb thanks for reporting
