### ISSUE TITLE
SpectorJS extension not working on latest Chrome version on MacOS

### ISSUE THREAD

**Issue by ibesora** [BabylonJS/Spector.js#313]
I'm using Chrome version 129.0.6668.91 on MacOS and it seems the latest update broke something on the SpectorJS Chrome extension side.
Clicking on the "Reload" button used to reload the website and start a capture immediately, opening the capture trace soon after the reload. Now it reloads the page but it doesn't open any capture.
Manually clicking on the capture button works but that doesn't work for my use case because I'm just rendering once.

You can test the behaviour in the [ThreeJS examples website](https://threejs.org/examples/#webgl_animation_keyframes) for example. 

Opening the Developer Tools on the extension shows the following errors:
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`
`Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by sebavan** [comment]
Thanks a lot for reporting it, I will fix it ASAP !!!

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Spector.js/commit/32d805a5e6d7d6dbb03fb509802e6c65e13aca39 will be deployed in a bit

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Spector.js/commit/32d805a5e6d7d6dbb03fb509802e6c65e13aca39 will be deployed in a bit
