### ISSUE TITLE
No frames get captured when I hit record

### ISSUE THREAD

**Issue by lax1dude** [BabylonJS/Spector.js#314]
Hi I'm trying to use this extension to take a capture of my app, its able to detect the canvas and lets me select it, but then when I press the record button it says `Capturing, be patient (this can take up to 3 minutes)...` but my app just continues to run at a solid 60fps like nothing is happening and as soon as I click out of the Spectator.js GUI and re-open it, it no longer says its trying to capture a frame. It's almost like the record button just displays some text and doesn't do anything else. My app does use `requestAnimationFrame` so I don't think the problem is that Spectator.js doesn't know when to capture a frame.

The only other potential issue is that I'm using `Function.prototype.bind` very early on all the WebGL context's functions to devirtualize them, because my app is in WASM and imports the OpenGL functions from JavaScript. Could it be the problem that Spectator.js works by replacing all of the WebGL context's functions some time after the context has already been initialized, and I'm binding all of them too early?

**Comment by sebavan** [comment]
Yup I am pretty sure it would be the issue :-( basically spector.js not capturing your calls cause it starts "spying" too late. You could try relying on the npm package instead and hook spector in before the use to bind. Please also note the .bind has quite a large cost in general and it could be amazing to avoid it in your app if possible.

Let me know if it is the issue you are facing.

**Comment by lax1dude** [comment]
> basically spector.js not capturing your calls cause it starts "spying" too late

I just tried changing the code not to use bind for any OpenGL functions, and it still doesn't capture anything, behavior is the same regardless if I use bind or not.

> Please also note the .bind has quite a large cost in general

I'll keep that in mind, when I tried testing it the browser did call a function I prepared with bind more quickly than a function I prepared by defining a wrapper, the stackoverflow post that says its "slower" to use bind is from like 10 years ago.

**Comment by lax1dude** [comment]
This is what I'm temporarily doing instead of using `bind` btw, if my understanding of JavaScript is correct this should allow Spectator.js to replace all the context object's functions after its already been created without causing this issue. I'm not sure why it still doesn't work.
```javascript
function doBind(ctxIn, fnName) {
    return function(...params) {
        return ctxIn[fnName](...params);
    };
}
```

**Comment by sebavan** [comment]
I can have a look if you can share a repro ?

**Comment by lax1dude** [comment]
> I can have a look if you can share a repro ?

I gave up and I was able to use RenderDoc to take a capture of the Chrome GPU process and debug my app that way. I don't have it set up anymore for Spectator.js and I can't share the link publically, and I don't want to eliminate `Function.prototype.bind` yet unless I can prove its actually slower in most cases. Thank you for trying to help me though.

**Comment by sebavan** [comment]
About bind, I thought I d check just to see if there is any diffs:
![image](https://github.com/user-attachments/assets/6f1ee21c-bbc5-4396-bfbf-eb6c5ae5759f)

Looks like it might still be a bit slower which is smthg we removed a couple years back in Babylon for some high frequency calls as it was introducing a perf issue.

**Comment by lax1dude** [comment]
@sebavan I see, there is a problem though with your test. In your lambda, you're just calling dosmthn directly instead of simulating dosmthn being a virtualized function that's part of a class, which gives the lambda an unfair advantage. In my case, if I were to use lambdas instead of bind I would be calling the functions by doing `context.func(params)` inside the lamba, which will obviously take longer than directly calling a function, and also have much less optimization potential from the JS engine too.

To accurately compare the lambda to bind for my use case, you would have to make dosmthn part of the prototype of a class, and call it by doing `obj.dosmthn()` in the lambda instead.

Anyway I will make sure to do a more comprehensive benchmark between bind and wrapper functions for the OpenGL imports, benchmarking them for my case is just a lot more nuanced than simply directly calling another non-virtual function from the lambda to test theoretical speed without bind.

**Comment by lax1dude** [comment]
@sebavan I finished manually testing bind vs lambda again with a prototype and several dummy parameters instead of calling a function directly, and using a lambda is less than 1% faster in that case (in V8). The simple benchmark you ran definitely gives the lambda an unfair advantage, bind seems to be every bit as performant as a lambda when it actually gets put to work.

**Comment by sebavan** [comment]
ohhh good to know !!! wonder why the following:

```
class foo {
	a = 0;
	
	add(val) {
		this.a += val;
	}
	
	mul(val) {
		this.a *= val;		
	}
	
	log() {
		console.log(this.a);
	}
}

const foo1 = new foo();
const add1 = (val) => {
	foo1.add(val);
};
const mul1 = (val) => {
	foo1.mul(val);	
};

const foo2 = new foo();
const add2 = foo.prototype.add.bind(foo2);
const mul2 = foo.prototype.mul.bind(foo2);
```

highlights quite a diff:
![image](https://github.com/user-attachments/assets/77d67f0c-e4c5-4ab9-88e1-2c86eeec71bc)

**Comment by lax1dude** [comment]
> highlights quite a diff

That's a pretty insane difference, after tweaking mine some more I'm back to getting better performance from bind than from the lambda. I get around 175ms from bind and about 200ms from the lambda.

```javascript

class MyObject {

	constructor() {
		this.v = 0;
	}

	add(v1, v2, v3) {
		this.v += v3;
	}

};

var obj = new MyObject();

const bindFunc = MyObject.prototype.add.bind(obj);

const lambdaFunc = function(v1, v2, v3) {
	obj.add(v1, v2, v3);
};

function doTest() {
	
	var a = 0;
	var b = 0;
	
	for(var j = 0; j < 20; ++j) {
		const s = performance.now();
		for(var i = 0; i < 1000000; ++i) {
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
			bindFunc(69.0, 420.0, 1337.0);
		}
		const ss = performance.now();
		
		const sss = performance.now();
		for(var i = 0; i < 1000000; ++i) {
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
			lambdaFunc(69.0, 420.0, 1337.0);
		}
		const ssss = performance.now();
		a += (ss - s);
		b += (ssss - sss);
	}
	
	console.log("bind: " + a);
	console.log("lambda: " + b);
}

```

This is in Chrome/V8. I guess I could try a proper benchmarking site instead of timing it myself, but I have a pretty deep distrust in what most JavaScript developers consider a valid benchmark so I've just timed it myself for now to avoid questioning what the benchmarking website does under the hood.

**Comment by lax1dude** [comment]
I'm calling my `doTest` function like 5 times first to "warm up" the JS engine before actually taking the results
