### ISSUE TITLE
TypeError: Array.prototype.slice called on null or undefined

### ISSUE THREAD

**Issue by NickPowers43** [BabylonJS/Spector.js#33]
Forgive me if Spector.js is not intended to work in any WebGL application including those which may not use WebGL correctly.

## The Issue
While working on a WebGL2 project I kept getting a null/undefined reference exception [here](https://github.com/BabylonJS/Spector.js/blob/d463232d82024fdf6e0379d143ca282d71a7d1cf/src/backend/states/drawCalls/drawCallState.ts#L254) when hitting the record button in the Spector.js Chrome extension.

It seems the call to gl.getVertexAttrib is returning undefined.

![image](https://cloud.githubusercontent.com/assets/1789999/26039483/5d3f9db0-38e9-11e7-9908-d0eab9cf46a8.png)

## A little background on the project
The goal of this project is to use the GPU to simulate the interaction between a collection of particles. Since the particles can interact with any other particle I have to use a combination of textures and VBOs to fetch the vertex attributes. For this reason the vertex positions are being stored in a texture and the rest are stored in the VBO since the position of the particles are the only relevant attributes to neighboring vertices. That means I have to setup a FBO as well as a transform feedback object to write the output of the simulation to both the VBO and the texture.

Here are the source files:
[main.js](https://pastebin.com/7xHT5xXT)
[particlesim.vs](https://pastebin.com/BfrVaMtR)
[particlesim.fs](https://pastebin.com/DHFBFeNw)

Despite calling `gl.uniform1i(positionTexLoc, theirTex);`
I get `RENDER WARNING: there is no texture bound to the unit 0`. Which I assume means the sampler in the vertex shader is not being set.

I predict this may be what is causing the error in Spector.js.

**Comment by sebavan** [comment]
Hello,

This looks like an interesting project you got.

As the main goal of Spector is to troubleshoot what happens in your context, it should definitely not crash in case of specific l usage like your case or even wrong use of the context. It should still help understanding what is happening.

I will fix it for the next release planned next week end. Thank you for reporting the issue.

Do you have an online page I could use to repro ?

Thx,

**Comment by NickPowers43** [comment]
Hi sebavan,

I plan on putting the project on Github. Let me do that and you can try it out. After further debugging I realized I was set my texture uniforms incorrectly so that is what was causing the `RENDER WARNING: there is no texture bound to the unit 0` warning.

**Comment by sebavan** [comment]
Thanks

**Comment by NickPowers43** [comment]
Here you go. Just run a simple web server in the root directory. https://github.com/NickPowers43/TreeOnTheHill

**Comment by sebavan** [comment]
Perfect thank you, I l fix it tomorrow evening and release this week end on Chrome

**Comment by sebavan** [comment]
sorry for the delay, won t be able to do it before the week end with the extension.

**Comment by NickPowers43** [comment]
No problem. Keep me posted.

**Comment by sebavan** [comment]
You can side load the extension to test, I ll publish soon the new version on the store.
