### ISSUE TITLE
The display of arguments of drawElements is incorrect

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Spector.js#35]
I traced triangle drawing by Babylon.js with Spector.js.
However, I noticed that the arguments of drawElements function are not displayed properly.
![image](https://cloud.githubusercontent.com/assets/1833979/26357616/cc54a362-400a-11e7-9797-668366baa304.png)

```
void gl.drawElements(mode, count, type, offset);
```
I think that `count` and `offset` arguments should not be displayed as constants.

**Comment by sebavan** [comment]
Funny you mentioned as I fixed it yesterday in https://github.com/BabylonJS/Spector.js/commit/a969158aa525db627e78e7aa04a3159ee9f10522

It has not been deployed to the store yet so you can sideload the extension if you require the fix. I will deploy this week end.

Thanks a lot for reporting the issue.

**Comment by cx20** [comment]
I confirmed that this problem has been fixed in latest Spector.js.
OS / Browser : Windows 10 + Chrome 58 + Spector.js v0.2.1
![image](https://cloud.githubusercontent.com/assets/1833979/26519630/a8fd1e88-42ff-11e7-9fec-91f3dc26bbdc.png)

However, unnecessary trace log (glp -> [object Object]) seems to be outputted. I think this is another issue.

**Comment by sebavan** [comment]
Thx for reporting, could you create a separate issue for this one ? it comes from the fact there are customs methods on your context and due to the naming I would bet on webgl insight plugin. you can try disabling it when using spector until a proper fix.
