### ISSUE TITLE
Installing the Spector.js add-on in Firefox will cause the shader editor to stop working

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Spector.js#37]
I tried installing Spector.js add-on in Firefox.
https://addons.mozilla.org/en-US/firefox/addon/spector-js/
However, Spector.js works but Firefox's shader editor does not work.
Disabling Spector.js add-on will cause the shader editor to work.

OS / Browser : Windows 10 + Firefox 53.0.3 + Spector.js v0.1.2
![image](https://cloud.githubusercontent.com/assets/1833979/26519817/f8734b7a-4301-11e7-8130-c7e56beffcf6.png)

![image](https://cloud.githubusercontent.com/assets/1833979/26519831/2dd35e4a-4302-11e7-91a5-bc48818da694.png)

![image](https://cloud.githubusercontent.com/assets/1833979/26519862/a24486e6-4302-11e7-9421-4acc7ae64b93.png)

**Comment by sebavan** [comment]
Thank you for reporting, I will see how i could fix it ? probably preventing the use of both at the same time.

**Comment by cx20** [comment]
Perhaps, these two tools (Spector.js and shader editor) may not be available at the same time.
I tried using the bundled version of Spector.js and shader editor but it seems that similar problems occur.

case1):
1. Please access [sample page](http://jsrun.it/cx20/G9YP) with Firefox.
2. Click the record button of Spector.js.
![image](https://cloud.githubusercontent.com/assets/1833979/26523409/efa14c86-4351-11e7-9be4-4eda0a8d1a61.png)
Spector.js works correctly.
![image](https://cloud.githubusercontent.com/assets/1833979/26523425/3d176fe0-4352-11e7-836c-32449b0f5a28.png)

case2):
1. Please access [sample page](http://jsrun.it/cx20/G9YP) with Firefox.
2. Display development tools with [Ctrl] + [Shift] + [I].
3. Click [Shader Editor] - [Reload] Button
![image](https://cloud.githubusercontent.com/assets/1833979/26523455/e5039d1e-4352-11e7-947b-dc49ab63c99f.png)
The shader editor works correctly.
![image](https://cloud.githubusercontent.com/assets/1833979/26523471/50043a56-4353-11e7-95df-8ab7ab60fb87.png)
4. Next, click the record button of Spector.js.
![image](https://cloud.githubusercontent.com/assets/1833979/26523476/6737ef1a-4353-11e7-99ad-46f980b91610.png)
An error is displayed and Spector.js does not function properly.
```
Error: Permission denied to access property "apply"
```

The following contents are displayed on the console.
```
Error: Permission denied to access property "apply"
スタックトレース:
n</t.prototype.getSpy/<@https://spectorcdn.babylonjs.com/spector.bundle.js:1:96297
s.prototype.setMatrix@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:5:6386
t.prototype.setMatrix@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:15:31484
i.prototype.bindOnlyWorldMatrix@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:25:12629
i.prototype.bind@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:25:12745
r.prototype.render@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:13:16663
t.prototype.render@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:14:5920
t.renderUnsorted@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:11:3798
t.prototype.render@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:11:2712
t.prototype.render@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:10:31753
i.prototype._renderForCamera@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:12:8993
i.prototype._processSubCameras@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:12:10256
i.prototype.render@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:12:14500
@http://jsrun.it/cx20/G9YP:213:5
s.prototype._renderLoop@https://cdnjs.cloudflare.com/ajax/libs/babylonjs/2.5.0/babylon.js:4:24554
t</e.prototype.getCallback/<@https://spectorcdn.babylonjs.com/spector.bundle.js:1:88861
 Array [  ]  spector.bundle.js:1:17116
```

**Comment by sebavan** [comment]
interesting indeed thx for the investigation. I really need to improve the overall compabillity with other extensions as well.

**Comment by sebavan** [comment]
@cx20 I am still trying to figure the best approach concerning this issue.

**Comment by sebavan** [comment]
I created a ticket on the Mozilla tracker as I am not sure this should happen (at least definitely not when the script is embedded in the page):

https://bugzilla.mozilla.org/show_bug.cgi?id=1372471

**Comment by DiThi** [comment]
As a workaround, you could avoid call/apply by storing the original functions in the same object. I usually do something like this:

```javascript
gl._uniform4fv = gl.uniform4fv;
gl.uniform4fv = function(loc, v){
    if(isNaN(v[0])) debugger;
    return this._uniform4fv(loc, v);
}```

but of course iterating through all functions, sometimes even using `new Function(...)` so it doesn't have to resolve the symbol on every call.

**Comment by sebavan** [comment]
Let me give it a try :-)

**Comment by sebavan** [comment]
It seems it could work but the main issue is I would have to remap all the calls manually which sounds pretty error prone. Do you have any other workarounds @DiThi ?

**Comment by DiThi** [comment]
@sebavan I think functions happily accept extra undefined arguments. Try just wrapping all functions before spector wraps them:

```javascript
for(var key in gl){
    var f = gl[key];
    if(typeof f === 'function' && !/^_orig_/.test(key)){
        gl['_orig_'+key] = gl['_orig_'+key] || f;
        gl[f] = new Function(`return this._orig_$key(
            arguments[0],
            arguments[1],
            arguments[2],
            arguments[3],
            arguments[4],
            arguments[5],
            arguments[6],
            arguments[7],
            arguments[8]
        );`);
    }
}
```

**Comment by sebavan** [comment]
@DiThi It seems I ll be able to fix it with your workaround. Just out of curiosity, any idea or pointers to why it works this way and not by relying on apply call or bind ?

I ll push the fix soon, still some cleanup and testing required.

**Comment by DiThi** [comment]
@sebavan My guess is that functions created in a privileged context forbid access to web contexts to anything but the most basic usage of these functions, to avoid sandbox escapes.

**Comment by sebavan** [comment]
@DiThi thanks for the explanation.
