### ISSUE TITLE
An unnecessary trace log is output in the latest version of Spector.js

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Spector.js#38]
I discovered that unnecessary trace logs will appear in the latest version of Spector.js.
Relate: https://github.com/BabylonJS/Spector.js/issues/35

OS / Browser : Windows 10 + Chrome 58 + Spector.js v0.2.1

How to reproduce the problem:

1. Install Spector.js from the Chrome Web Store.
https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk
2. Please access the [WebGL sample page](http://jsrun.it/cx20/84AP) with Chrome.
3. Start the Spector.js extension from the toolbar.
![image](https://cloud.githubusercontent.com/assets/1833979/26523663/2cc3e7f4-4357-11e7-991d-186a2460ab26.png)
Unnecessary trace log (glp -> [object Object]) seems to be outputted. 
![image](https://cloud.githubusercontent.com/assets/1833979/26523613/687c4288-4356-11e7-82ae-434bbb4a3f2f.png)

**Comment by sebavan** [comment]
Seems to be linked to the fact that other extensions are also tracking the context (probably weblglinsight) I need to figure out how to split between the real log and the other extensions commands.

**Comment by cx20** [comment]
I confirmed that the path output to Stack Trace matches the ID of `WebGL Insight`.
```
Stack Trace
0: WebGLRenderingContext.default (chrome-extension://djdcbmfacaaocoomokenoalbomllhnko/src/content_script/fcn_bindings.js:7:12)
1: WebGLRenderingContext.drawElements (chrome-extension://djdcbmfacaaocoomokenoalbomllhnko/src/content_script/webgl_bind.js:10:24)
2: WebGLRenderingContext.drawElements (<anonymous>:1:96314)
3: h.draw (http://jsrun.it/assets/3/W/f/g/3WfgZ:4:8704)
```
![image](https://cloud.githubusercontent.com/assets/1833979/26527919/cd75f0f8-43d8-11e7-94a5-8f4e18bc113c.png)

I tried to disable the "WebGL Insight" Chrome extension, and unnecessary trace logs are no longer output.

**Comment by sebavan** [comment]
@cx20 I am still trying to figure the best approach concerning this issue.

**Comment by sebavan** [comment]
Explicitly removed those internals commands.
