### ISSUE TITLE
WebglConstant displays in Viewport and Scissor Command format.

### ISSUE THREAD

**Issue by sebavan** [BabylonJS/Spector.js#40]
https://twitter.com/mrdoob/status/872231440150286336

**Comment by DiThi** [comment]
This happens for `uniform1i` too, so it possibly happens for some other `uniform*` functions as well.

**Comment by sebavan** [comment]
This has been fixed for uniforms here: https://github.com/BabylonJS/Spector.js/commit/e3914a44165d1a10f1ba6e6dfa239b8321e7895d

It is yet to be deployed to the store. You can sideload during this time.
