### ISSUE TITLE
Triangles, Lines and Points count.

### ISSUE THREAD

**Issue by mrdoob** [BabylonJS/Spector.js#43]
Any chance the extension could count the amount of triangles, lines and points drawn?

**Comment by sebavan** [comment]
I ll add the split for the entire frame in the information panel just aside the total primitives number.

**Comment by sebavan** [comment]
![image](https://user-images.githubusercontent.com/16655165/27371671-96d6cad6-5616-11e7-8f7a-410fe3864ce6.png)

This is how it looks, I plan to deploy soon, still working on the command comparison. In the mean time, feel free to side load the extension if needed.

**Comment by mrdoob** [comment]
Nice!

**Comment by marquizzo** [comment]
Question, does this total include triangles that were not drawn due to backface culling?

**Comment by sebavan** [comment]
Yup, it includes all counts passed through the "draw" functions
