### ISSUE TITLE
Feature request: tagging specific code locations with strings

### ISSUE THREAD

**Issue by erich666** [BabylonJS/Spector.js#45]
In some debug and performance tools for the GPU you can tag code with a label. That is, you might be entering, say, a blur pass and you want to know that's where you are when you see the dump of command in Spector.js. You make a debug call at that point, and Spector.js would display the label you've put as a string, e.g.

`spector.label('GaussianBlur');`

This code does nothing, but Spector.js would print out the label in the command stream shown in debug.

Anyway, there are obviously issues with the format above, since Spector instruments the code, but some way to add dummy code that Spector would use as labeling would be nice. Currently I'm finding I have to do things like count the number of clear commands encountered - ugh. I know about how you can label buffers, but that's different than labeling code locations. Buffers might get reused, a code location gives a specific execution location.

There might also be some WebGL command that I could use instead, some essentially no-operation API command that lets me pass in a string. That would be a kludge, but I'd be happy to use one, if anyone thinks of a way to do this.

**Comment by sebavanmicrosoft** [comment]
Amazing idea, fully aligned with my next iteration which about adding capture() keywords to force capturing without the menu so you could capture preprocessing or loading from your scenes or the first frame for instance.

I ll do it in a couple of weeks when I ll finalize my next version of Spector.

**Comment by erich666** [comment]
I look forward to it! (Though I was briefly disappointed to see this "closed" but not yet done - I thought maybe the feature was now in, but it's only on the TODO list. Still, soon! I appreciate you adding it, and I've put a reminder on my calendar to check in next month.)

**Comment by sebavan** [comment]
The feature is in, but not deployed to the extension store. You can on the new version (if you sideload) call spector.setMarker("marker") and spector.clearMarker() in your code (spector is available on the window if activated)  and the markers will be visible in the result commands (green flashy text in front of the command):
![image](https://user-images.githubusercontent.com/16655165/29243559-51b8efb0-7f56-11e7-8dda-fc7730c69f19.png)

More documentation is yet to come for the new programmatic aspect.

**Comment by sebavan** [comment]
@erich666, this is now deployed to the store and the documentation is here: https://github.com/BabylonJS/Spector.js/blob/release/documentation/extension.md#how-to-use

**Comment by erich666** [comment]
Great, I've cleaned it up a little and added it to the Getting Started guide: http://www.realtimerendering.com/blog/debugging-webgl-with-spectorjs/ - I should do a PR to fold my fixes into your page, but hope you'll edit your page instead.

**Comment by sebavan** [comment]
Perfect, I ll integrate in the doc :-)
