### ISSUE TITLE
Feature request: programmatic control of Spector captures

### ISSUE THREAD

**Issue by erich666** [BabylonJS/Spector.js#46]
I am often dealing with complex problems where a particular condition sets off a particular graphics bug or warning. I would love it if I could turn Spector's capture on and off as needed. That is, I might have

if ( cursor location over particular part ) { Spector.beginRecording(); }

possibly with optional arguments if you want to get fancy, and maybe 

if ( Spector.isRecording() ) { Spector.endRecording(); }

If other words, some way to see if we're currently recording so that we could turn it off (or just allow Spector.endRecording() to be called and do nothing if not recording). You'd want to think this through, of course, e.g., what happens if two begins are hit, or no end method is encountered (I'm not quite sure what triggers "end of frame" currently).

**Comment by sebavan** [comment]
Makes total sense and will be part of the next version as well.
