### ISSUE TITLE
better stacktraces support?

### ISSUE THREAD

**Issue by makc** [BabylonJS/Spector.js#47]
more like feature request, I guess - in firefox there are no stack traces, in chrome stack traces are present but not clickable.

**Comment by makc** [comment]
the problem with [current code](https://github.com/BabylonJS/Spector.js/blob/7a706f74dad751e8228cb13a33fe062c201d406c/src/shared/utils/stackTrace.ts#L21-L46) is the regexp /^\s*[A-Za-z0-9\-_\$\]+\(/ - it matches chrome format
> window.onload (https://fiddle.jshell.net/_display/:45:11)

but does not match firefox format
> window.onload@https://fiddle.jshell.net/_display/:45:11

the only point in having this check would be to skip 1st line in chrome, I guess?

p.s. you dont have to throw the error, just do `let err = new Error;`

**Comment by sebavan** [comment]
Cool Thanks for the feedback, I ll fix in the next version.

**Comment by makc** [comment]
actually I was wrong, the chrome case is handled by "    at " case. Idk what does that regexp match?

**Comment by sebavan** [comment]
I ll double check it on more browsers, It was probably matching with old versions. This will never be safe anyway :-) but there are no available APIs in js for this.
