### ISSUE TITLE
fails to capture anything that requires user interaction

### ISSUE THREAD

**Issue by makc** [BabylonJS/Spector.js#48]
I want to press red button, go back to my page and do stuff, then go back to spector and press stop button - much like in js profiler. instead I get a message saying to render stuff non-stop or gtfo.

**Comment by sebavan** [comment]
This will be addressed by #46 where you could programatically on your action or from the console start a capture. We will still limit the capture to one frame due to their potential size.

**Comment by makc** [comment]
what's "one frame" though? clear() call?

**Comment by makc** [comment]
> due to their potential size.

why not limit explicitly capture size then. like auto-stop when you saved 50 mb of data or something

**Comment by sebavan** [comment]
Each capture is easily around 150 Mb for a frame. I consider a frame every calls happening between the starts of the requestAnimationFrame callback and its end. It could also be a setTimeout of 0, 16ms...

Basically all the calls I am trying to capture participating to create a visual frame.

The programmatic aspects could be pretty close from the ```debugger;``` keyword in js or at least I hope.

I may try to add more options later for the capture but in v1.

**Comment by sebavan** [comment]
this will be address by https://github.com/BabylonJS/Spector.js/issues/46 this weekend.
