### ISSUE TITLE
Keyboard keys to navigate API call and canvas framebuffer lists?

### ISSUE THREAD

**Issue by juj** [BabylonJS/Spector.js#54]
When having clicked the keyboard focus to be on a API call, as follows:

![10kcubes](https://user-images.githubusercontent.com/225351/29160370-a0655966-7dba-11e7-8065-952ac20fe58f.png)

It would be nice to be able to use keyboard Up and Down keys to navigate between adjacent API calls, and for example Ctrl-Up and Ctrl-Down to navigate to next/previous draw call.

Similarly, when clicking on the left hand side on a "Canvas frame buffer" icon, it would be nice to be able to use Up and Down keys to navigate between frame buffer states.

Currently Up and Down keys seem to always scroll the API call list view without moving the keyboard focus.

**Comment by sebavan** [comment]
Would be nice to add, I ll keep it for the version 2

**Comment by sebavan** [comment]
Done by using arrow up/down for command navigation and page up/down for visual states (Clear/Draw calls)

**Comment by sebavan** [comment]
Commit Reference: https://github.com/BabylonJS/Spector.js/commit/52bf176f30dc7dd4652ff0acaf5e952b7f8c4422
