### ISSUE TITLE
disableVertexAttribArray input interpreted incorrectly

### ISSUE THREAD

**Issue by juj** [BabylonJS/Spector.js#55]
It looks like the `index` parameter in calls to `GL.disableVertexAttribArray(index)` is incorrectly interpreted as an enum for `GL.drawArrays` primitive type. See the following screenshot:

![10kcubes](https://user-images.githubusercontent.com/225351/29160659-dbc0942a-7dbb-11e7-8b2b-e3f105dbf6eb.png)

which reads

```
disableVertexAttribArray: TRIANGLES
disableVertexAttribArray: TRIANGLE_STRIP
```

whereas it should read

```
disableVertexAttribArray: 4
disableVertexAttribArray: 5
```

**Comment by juj** [comment]
It looks like `enableVertexAttribArray` has the same behavior, though some indices some out properly as numbers, only others get the number mistranslated to an enum name.

**Comment by sebavan** [comment]
I ll fix it ASAP

**Comment by sebavan** [comment]
Fixed by https://github.com/BabylonJS/Spector.js/commit/fd0080cda99bc1b33215812b3da264bf6e697ad7
