### ISSUE TITLE
Allow seeing several captures side by side

### ISSUE THREAD

**Issue by DiThi** [BabylonJS/Spector.js#58]
Captures are always open in the same tab. As a workaround I open the browser as a different user, capture whatever, and then open the .json captured previously.

Also, at least in linux with chromium-browser, I can't drag a file to the spector pop up (that's why I have to go to some webgl example to capture).

**Comment by sebavan** [comment]
You can use the checkbox of the popup to create the capture in a new tab. This will also be the default behavior in the next version.
