### ISSUE TITLE
Documentation for multiple captures is unclear

### ISSUE THREAD

**Issue by erich666** [BabylonJS/Spector.js#61]
I want to put different captures in different windows. How do I easily do so? That is, I make a capture, I make another capture. The second capture replaces the first, in the same window. There used to be a feature where you would click the box "Open in new tab", as documented [here](http://www.realtimerendering.com/blog/debugging-webgl-with-spectorjs/), but I don't see that option. What's the "easy" way I'm supposed to use to make separate windows? I'll update the documentation accordingly.

**Comment by sebavanmicrosoft** [comment]
Hello,

They should now always open in a new tab as a few people suggested and the option disappeared to open in a new tab was then removed. What browser are you using (it seems to be a bug if this opens in the same tab) ?

**Comment by erich666** [comment]
Windows 7, Chrome, and I'm using `spector.captureNextFrame(_this.canvas);` to capture the frame. It always goes to the same window. The various captures are properly stored in Captures, but each appears in the same window.

**Comment by erich666** [comment]
And doing a little more testing, that appears to be it, using captureNextFrame. If I use the "red button" method, each capture opens a new window.

**Comment by sebavan** [comment]
Ohhhhhh right, I did not check from the programmatic mode. I ll fix it ASAP.

**Comment by sebavan** [comment]
Sorry for the delay it should be available soon on the extension store
