### ISSUE TITLE
Module Use Error: "No frames detected. Try moving the camera or implementing requestAnimationFrame."

### ISSUE THREAD

**Issue by kevzettler** [BabylonJS/Spector.js#66]
I am trying to use the `spectorjs` module.

```javascript
      const s = new SPECTOR.Spector();      
      s.displayUI(); 
```

This renders the Spector UI:

<img width="433" alt="screenshot 2017-09-21 14 36 21" src="https://user-images.githubusercontent.com/126209/30719893-4573dbfe-9eda-11e7-80ca-f09d3ccbd122.png">

When I try to record I get the error.

`No frames detected. Try moving the camera or implementing requestAnimationFrame.` I definitely have requestAnimation frame running. The UI detects multiple canvas's on the page. One of them being the correct webgl canvas.

**Comment by sebavan** [comment]
Could you share a repro ? If it is your page, you could add an id on the canvas so that it will help you figuring which one it is in the list.

**Comment by kevzettler** [comment]
@sebavan here is a repro:

http://requirebin.com/?gist=f040fcc0c708aa9f6fb4e011ea3d1d58

It seems I can isolate it the issue to creating the `canvas` element using `React` not sure why that would prevent the Spector.js from picking it up? It still gets rendered to the DOM with an ID and is detected by the `spector.displayUI`

Additionally the spector.js browser extension is able to correctly hook into it.

**Comment by sebavan** [comment]
The automatic detection is a bit different in the extension and the embedded version. I ll check what I can do about it over the week end. But basically in the extension canvas are checked when the popup open and in the embedded based on getContext requests.

**Comment by kevzettler** [comment]
thanks a lot, @sebavan.  I can definitely try to debug as well. If you could point me to the relevant code you suspect i'll take a look

**Comment by sebavan** [comment]
@kevzettler , the code is ok but Spector needs to be instantiated before the require(loop) to work.

Actually, "Loop" is relying on the method Spector is meant to hijack to detect fram like requestAnimationFrame. So if it is defined before Spector, we hijack simply too late after it has been used.

This fixes it:
https://gist.github.com/sebavan/365818757046dfe075d536a717f711f5

**Comment by kevzettler** [comment]
@sebavan this did not help fix my production case. I have moved the init code:
```
import SPECTOR from 'spectorjs';
const s = new SPECTOR.Spector();
s.displayUI();   
```

to the head of the file it is utilized in.

Is there any way to manually init or specify a GL context to pass to Spector?

**Comment by sebavan** [comment]
Most of the api for programmatic access are available here: https://github.com/BabylonJS/Spector.js/blob/master/documentation/apis.md

you can even start the capture by code which would be simpler.

Let me know if that works.

**Comment by pasu** [comment]
Hi, the same problem here:
https://esri.github.io/cim-symbol-builder-js/

**Comment by JannikGM** [comment]
@pasu your problem seems to be a different one.

Spector.js detects a frame but crashes in `stencilFunc` / `formatBinary`, probably because wrong number of arguments or just a bad stencil?

Stack is a bit weird, too (spector.js capturing itself?), but that might be a Chrome bug as my devtools crash when navigating the stack.

**Comment by pasu** [comment]
@JannikGM Thank you for your sharing, that makes sense. 
In my case, I want to get how arcgis js use the texture of the CIMSymbol after rasterization.

**Comment by odoe** [comment]
I don't want to clutter this issue, but @pasu please make an issue here https://github.com/Esri/cim-symbol-builder-js for your issue.
The ArcGIS team is going to be looking at the original issue raised here, so thank you very much @JannikGM for help narrowing it down. Our WebGL devs will take a closer look. Thanks!

**Comment by sebavan** [comment]
@JannikGM I guess we should protect against crashes anyway on the spector side as well. Would you be up to PR that ?

@odoe and @pasu I love that spector and the community helped you narrow down the issue !!!

**Comment by JannikGM** [comment]
@sebavan Sorry, I currently don't have any time budget in the foreseeable future to work on Spector.js

**Comment by sebavan** [comment]
No problem, I will do it tonight :-)

**Comment by sebavan** [comment]
Done, this would make those calls safer: https://github.com/BabylonJS/Spector.js/commit/708f1f7063b240a8f0bd4f31ea281ef91bc88073
