### ISSUE TITLE
Error in result page in ubuntu firefox

### ISSUE THREAD

**Issue by sanjok-bless** [BabylonJS/Spector.js#70]
Hello, everybody!

I am trying to save spector results in ubuntu firefox (try 56 and 57 versions). But an error occurs on result page:

`The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.`

And save method doesn't triggered if I click to save button.

Can you add `<meta charset="utf-8"/>` in the head of extensions/result.html to fix this?

**Comment by sebavan** [comment]
This shall be done ;-)
