### ISSUE TITLE
TimeSpy setTimeout doesn't support additional parameters

### ISSUE THREAD

**Issue by clevea** [BabylonJS/Spector.js#81]
The additional parameters that get passed to the timeout function are included in the setTimeout implementation in TimeSpy. My application which uses these parameters crashed when they weren't present.

I was able to work around the problem using a scoped variable, but thought I would raise it as an issue.

**Comment by sebavan** [comment]
Thanks for reporting it, i will fix it ASAP. I completely missed this case.

**Comment by sebavan** [comment]
@clevea ,  The previous commit fixed the issue, you can sideload the extension for the time being I will release the new version by end of month.

**Comment by anlumo** [comment]
Just stumbled upon this issue… took me an hour to locate Spector as the culprit, since the exception is just in a VM12535 minified file.

Please update the store version!
