### ISSUE TITLE
Add shortcut to record

### ISSUE THREAD

**Issue by vlucendo** [BabylonJS/Spector.js#82]
First of all thank you for this great extension, it has changed the way I work completely :)

Sometimes is hard to capture what's happening in a specific moment (transitions that use FBOs conditionally, etc), when elements are triggered by user input (holding a mouse button, moving the cursor, etc).

For these kind of situations it would be really handy a keyboard shortcut to start recording, this way it would be possible to activate the transition/effect with the mouse and record it immediately.

**Comment by sebavan** [comment]
Good idea :-) I ll add it in 2.0 in the mean time, feel free to use the programmatic api from the dev tools console: https://github.com/BabylonJS/Spector.js/blob/master/documentation/extension.md#how-to-use
 startCapture() and stopCapture() should do.
