### ISSUE TITLE
Extension popup doesn't work on secondary screen

### ISSUE THREAD

**Issue by anlumo** [BabylonJS/Spector.js#83]
OS: Windows 10 Creators Edition
Browser: Chrome 62

When my browser window is open on a secondary screen, I can open the extension's popup in the toolbar, but none of the elements there reacts on mouse clicks. I have to move the window to the main screen to work around this.

I suspect that the mouse position calculation is off for some reason (wrong origin of the screen?), so the hit detection doesn't work.

**Comment by sebavan** [comment]
This is a known Chrome issue with multiple screens of different DPIs:
https://bugs.chromium.org/p/chromium/issues/detail?id=715552 which is a dup of https://bugs.chromium.org/p/chromium/issues/detail?id=659642

Closing since I can not handle it here...
