### ISSUE TITLE
Inspector Error

### ISSUE THREAD

**Issue by Ericky14** [BabylonJS/Spector.js#84]
I get an error when I try to run the babylon inspector with 

```scene.debugLayer.show();```
And it only happens when I go to the GUI tab.

```
"babylonjs": "3.1.1",
"babylonjs-gui": "^3.1.1",
```

![5a3c805f6502b_screenshot2017-12-21at10_44_35pm thumb png 059b0fd540355107064545fd46a57edd](https://user-images.githubusercontent.com/21248862/34360414-a6cf3c78-ea2e-11e7-897d-94e6b64bb4ef.png)

**Comment by RaananW** [comment]
Hi @Ericky14 ,
I tried reproducing this and couldn't. Could you share the scene or show an example in the playground?

Would be great if you answered here - https://github.com/BabylonJS/Babylon.js/issues/3449 , so we can keep a track on the issue.
