### ISSUE TITLE
Observe page for context creations?

### ISSUE THREAD

**Issue by luruke** [BabylonJS/Spector.js#85]
I'm using the Browser extension under Chrome, and I have few project where the webgl canvas and context are created after the loading.

This results in Spector not "catching" the context, and the icon stays gray.

Can this be considered a bug?
What would be the best way to use the browser extension in this case?

**Comment by sebavan** [comment]
Yup I agree it is annoying and I have the same issue with Poly where the Canvas is off screen.

Could you send me a repro to ensure the solution I am planing to do works in your case ?

I was waiting to push a new version for remote debug but never found the time.  I ll push a new version soon as there are a few issues I wanted to address.

**Comment by luruke** [comment]
Hello @sebavan ,
One live example could be this: http://letsplay.ouigo.com

**Comment by sebavan** [comment]
Ok perfect, i ll ensure we can capture do something for it.

**Comment by sebavan** [comment]
@luruke I am almost done with the fixes I ll update the plugin tomorrow night I have added a mode to capture any canvases creating a 3d context.

**Comment by luruke** [comment]
Great, thank you @sebavan 
I'll make sure to test it.

**Comment by sebavan** [comment]
@luruke It should be all godd, I have pushed the new release to the store.

Let me know if you have any issues.

**Comment by luruke** [comment]
Great! thank you @sebavan
