### ISSUE TITLE
Link to shader is not displayed when tracing CZPG.js

### ISSUE THREAD

**Issue by cx20** [BabylonJS/Spector.js#89]
I traced a cube sample using CZPG.js which is a WebGL 2.0 compatible library with Spector.js.
http://jsdo.it/cx20/2UIh

However, it seems that the link to the shader does not appear in the trace result.
![image](https://user-images.githubusercontent.com/1833979/39711187-f3632322-5259-11e8-8305-cd5028d1e5dd.png)

I have not been able to isolate whether this is a problem of Spector.js or a library problem.

/cc @PrincessGod

**Comment by sebavan** [comment]
Hello @cx20 ,

It is expected as the shader have been detached from the program by calling the detachShader command. Spector can then not access the currentShaders through the getAttachedShaders command.

That said, I totally understand the issue and I am wondering if I should save the shader associated to a program during its creation ?

Funny thing is it seems that most of the people are not detaching the shaders before and basically waits for the program deletion instead.

BR,

**Comment by cx20** [comment]
@sebavan Thank you for telling me about `detachShader`. 
I understood that it is the specification at the present moment.

Also, I confirmed that shader can be displayed in Spector.js by commenting out the line below.
https://github.com/PrincessGod/CraZyPG/blob/cbf21ff435629a5c766a87eccf1e3ba4737c0b05/src/renderer/program.js#L101-L104
```javascript
/*
    gl.detachShader( prog, vShader );
    gl.detachShader( prog, fShader );
    gl.deleteShader( vShader );
    gl.deleteShader( fShader );
*/
```
![image](https://user-images.githubusercontent.com/1833979/39763194-70edbca4-5317-11e8-98f3-37aba2d9ce90.png)

**Comment by PrincessGod** [comment]
great job, I am using spector on CZPG recently, this message really helpful.

**Comment by thomlucc** [comment]
Closed as there is a workaround and the pattern isn't used enough.
