### ISSUE TITLE
Didn't recognize drawArraysInstancedANGLE()

### ISSUE THREAD

**Issue by dangif** [BabylonJS/Spector.js#91]
It doesn't recognize call to drawArraysInstancedANGLE (WebGL 1) and don't add frame buffer screenshot.  

E.g. it works on https://threejs.org/examples/?q=inst#webgl_buffergeometry_instancing_billboards where is:
drawElementsInstancedANGLE: TRIANGLES, 18, UNSIGNED_SHORT, 0, 75000

but doesn't work on https://threejs.org/examples/?q=inst#webgl_buffergeometry_instancing where is 
drawArraysInstancedANGLE: TRIANGLES, 0, LINE_STRIP, 50000

**Comment by sebavan** [comment]
Thanks for reporting it I ll fix and deploy it ASAP.

**Comment by sebavan** [comment]
Sorry for the HUGGGGGGGGGGGGGEEEEEEEE delay.

You can already use it from the local version. I ll try to deploy on the store this week end.
