### ISSUE TITLE
Spector js can not find my 3D canvas in my webpage

### ISSUE THREAD

**Issue by briangavin** [BabylonJS/Spector.js#92]
Spector js works for me on other websites with webgl and the spector extension recognizies my webpage uses webgl but whey I try to choose a canvas there are none on the list.    The canvas is buried fairly deeply in some html elements maybe that is part of the problem.   Is there a way I can hack it to find my canvas so I can use this great tool.

**Comment by sebavan** [comment]
Is it possible to access your page in order to check what is happening ? (of course if it is public)

Else you could use the code version (not the extension) as specified here: https://github.com/BabylonJS/Spector.js#use-as-a-module

**Comment by briangavin** [comment]
I figure out the cause.   I was running Firefox in a private window once I switched to non private window the canvas appear.   

Unfortunately all it seemed to capture is the final rendered image.   I using my own webgl engine not babylonjs.   Not sure why I do not see the draw steps.

You might want to add something to your documentation saying not to run in private window mode in Firefox.

**Comment by sebavan** [comment]
Thanks for the feedback, and yes I guess extension a bit intrusive might be disabled in private mode.

This is still pretty strange you are not capturing the full frame.

Let me know if I can help resolving this.
