### ISSUE TITLE
Chrome extension breaks debugger

### ISSUE THREAD

**Issue by bunnybones1** [BabylonJS/Spector.js#95]
Hey guys,

I've recently narrowed down a breakage in chrome's debugger to this extension. Having this extension enabled makes debugging with the stack trace nearly unusable. 
Here is an example of debugging a stack during a paused exception. Everything as normal.
<img width="314" alt="screen shot 2019-01-04 at 10 48 14 pm" src="https://user-images.githubusercontent.com/453513/50720052-bb3aff00-1073-11e9-9447-c9cec96af1e4.png">
Here is the same error but with SpectorJS enabled.
<img width="314" alt="screen shot 2019-01-04 at 10 47 58 pm" src="https://user-images.githubusercontent.com/453513/50720064-005f3100-1074-11e9-9994-d487724a32ee.png">

For now my workaround is to only enable the extension when I need to inspect the WebGL commands, otherwise I keep it disabled.

**Comment by sebavan** [comment]
Unfortunately Spector is working as a middle man sniffing all the contexts calls once enabled. 

Is it happening also when spector has not been enabled (by clicking on the icon) ?

The icon should have a red dot in this case.

**Comment by bunnybones1** [comment]
I'm not sure how to disable it once it's been enabled. Whenever I refresh my browser, the spector.js icon automatically turns green (as soon as it gets a WebGL context I think)

**Comment by sebavan** [comment]
It should disable itself (staying red) as soon as you close the tab. is it not the case ?

**Comment by sebavan** [comment]
Is it ok for you now @bunnybones1 ?

**Comment by bunnybones1** [comment]
@sebavan It stays red if I haven't enabled it for that tab, but even a hard refresh on that tab doesn't disable it. I can see why this would be preferable for most iterative workflows. I can live with it.

**Comment by sebavan** [comment]
Ok great closing the issue then Thanks
