### ISSUE TITLE
show wire frame just like nvidia nsight?

### ISSUE THREAD

**Issue by yafacex** [BabylonJS/Spector.js#96]

**Comment by yafacex** [comment]
Is it possible inject glEnable(0x0B41)  to current selected draw call  so that the shape is easily be recognized?

**Comment by sebavan** [comment]
I would love to do it but did not find any easy way to do it so far.

I tried replacing the draw mode and so on for lines only but it is messing the Render Target and does not bring a lot as a result.

I guess the only way would be to track/copy the buffer infos to be able to introspect them like I should do for textures.

About POLYGON_SMOOTH it unfortunately does not exist in WebGL

**Comment by sebavan** [comment]
I am taking any ideas for wireframe :-)

**Comment by sebavan** [comment]
Closing as Spector can not modify data, only looking through them.

Shader is a particular exception but it actually works through through the inspected app. Spector itself does not interfer with the render loop.
